--!nonstrict
-- Service behaviour tests: plugin/restic-snapshots/service.luau driven for real.
-- Run from the repo root:  lua5.4 tests/lua/service_test.lua
--
-- The service owns the things a backup plugin can get dangerously wrong, so these tests drive
-- the real entry (not a copy of its logic) through the harness and assert on what it published:
--   * a run missed while the shell was off is caught up, and a reload never pushes a backup
--     forward (review finding: "a restart could push a backup forward forever");
--   * a hung restic is struck down, reported as a timeout and cannot block the next run
--     (finding: "a hung restic blocked every future run");
--   * a cancel is a cancel, and a failure is actually visible (finding: "a failed job never set
--     status.error, so a cancel looked exactly like a failure");
--   * a repository that has quietly stopped being backed up is noticed, once, in observe mode
--     too (the feature that would have caught a real missed backup).

package.path = "tests/lua/?.lua;" .. package.path
local H = dofile("tests/lua/harness.lua")

local failures = 0
local function check(name, condition, detail)
  if condition then
    print("ok   " .. name)
  else
    failures = failures + 1
    print("FAIL " .. name .. (detail ~= nil and ("  -- " .. tostring(detail)) or ""))
  end
end

local NOW_MS = 1788874602000
local NOW_SEC = 1788874602
local JOB_DIR = "/tmp/restic-data/jobs"
local STATE_PATH = "/tmp/restic-data/state.json"

-- Timestamps used by the staleness section, in the offset form restic emits.
local OLD_TIME = "2026-09-08T03:36:42+00:00"    -- NOW - 10h  (epoch 1788838602)
local FRESH_TIME = "2026-09-08T13:35:42+00:00"  -- NOW - 60s  (epoch 1788874542)

-- ── a real JSON decoder ──────────────────────────────────────────────────────
-- The store writes state.json and the service reads it back, so "does the schedule survive a
-- restart" cannot be tested against a canned table map: the text is generated by the encoder.

local decodeJson
do
  local function skipSpace(text, pos)
    while true do
      local c = text:sub(pos, pos)
      if c == " " or c == "\t" or c == "\n" or c == "\r" then
        pos = pos + 1
      else
        return pos
      end
    end
  end

  local function parseValue(text, pos)
    pos = skipSpace(text, pos)
    local c = text:sub(pos, pos)
    if c == "{" then
      local out = {}
      pos = skipSpace(text, pos + 1)
      if text:sub(pos, pos) == "}" then
        return out, pos + 1
      end
      while true do
        local key, value
        key, pos = parseValue(text, pos)
        pos = skipSpace(text, pos)
        if text:sub(pos, pos) ~= ":" then
          error("expected : at " .. pos)
        end
        value, pos = parseValue(text, pos + 1)
        if value ~= nil then
          out[key] = value
        end
        pos = skipSpace(text, pos)
        local sep = text:sub(pos, pos)
        if sep == "," then
          pos = pos + 1
        elseif sep == "}" then
          return out, pos + 1
        else
          error("expected , or } at " .. pos)
        end
      end
    elseif c == "[" then
      local out = {}
      pos = skipSpace(text, pos + 1)
      if text:sub(pos, pos) == "]" then
        return out, pos + 1
      end
      while true do
        local value
        value, pos = parseValue(text, pos)
        table.insert(out, value)
        pos = skipSpace(text, pos)
        local sep = text:sub(pos, pos)
        if sep == "," then
          pos = pos + 1
        elseif sep == "]" then
          return out, pos + 1
        else
          error("expected , or ] at " .. pos)
        end
      end
    elseif c == '"' then
      local out = {}
      pos = pos + 1
      while true do
        local ch = text:sub(pos, pos)
        if ch == "" then
          error("unterminated string")
        elseif ch == '"' then
          return table.concat(out), pos + 1
        elseif ch == "\\" then
          local esc = text:sub(pos + 1, pos + 1)
          if esc == "n" then
            table.insert(out, "\n")
          elseif esc == "t" then
            table.insert(out, "\t")
          elseif esc == "r" then
            table.insert(out, "\r")
          elseif esc == "u" then
            table.insert(out, utf8.char(tonumber(text:sub(pos + 2, pos + 5), 16) or 63))
            pos = pos + 4
          elseif esc == "b" then
            table.insert(out, "\b")
          elseif esc == "f" then
            table.insert(out, "\f")
          else
            table.insert(out, esc)
          end
          pos = pos + 2
        else
          table.insert(out, ch)
          pos = pos + 1
        end
      end
    elseif text:sub(pos, pos + 3) == "true" then
      return true, pos + 4
    elseif text:sub(pos, pos + 4) == "false" then
      return false, pos + 5
    elseif text:sub(pos, pos + 3) == "null" then
      return nil, pos + 4
    end
    local stop = pos
    while stop <= #text and text:sub(stop, stop):match("[%d%.eE%+%-]") do
      stop = stop + 1
    end
    local number = tonumber(text:sub(pos, stop - 1))
    if number == nil then
      error("bad value at " .. pos)
    end
    return number, stop
  end

  decodeJson = function(text)
    if type(text) ~= "string" then
      return nil
    end
    local ok, value = pcall(parseValue, text, 1)
    if not ok then
      return nil
    end
    return value
  end
end

local function readState()
  local text = H.files[STATE_PATH]
  if type(text) ~= "string" then
    return nil
  end
  return decodeJson(text)
end

-- ── harness plumbing ─────────────────────────────────────────────────────────

local DEFAULTS = {}
for key, value in pairs(H.config) do
  if type(value) == "table" then
    local copy = {}
    for k, v in pairs(value) do
      copy[k] = v
    end
    DEFAULTS[key] = copy
  else
    DEFAULTS[key] = value
  end
end

local runner = { pairs = {} }
local snapshotJson = "[]"
local snapshotExit = 0
local snapshotStderr = ""

local function argvHas(cmd, needle)
  for _, value in ipairs(cmd) do
    if value == needle then
      return true
    end
  end
  return false
end

-- Answer every read-only runAsync the service issued, classifying it by argv. A callback that
-- issues more work (the login-path probe resolves restic and refreshes) is drained in turn, so a
-- single call settles the service the way a settled shell would.
local function drain()
  local answered = 0
  while #runner.pairs > 0 do
    local batch = runner.pairs
    runner.pairs = {}
    for _, entry in ipairs(batch) do
      local cb = entry.cb
      if cb ~= nil then
        answered = answered + 1
        local cmd = entry.cmd
        local result = { exitCode = 0, stdout = "", stderr = "" }
        if cmd[1] == "sh" then
          result.stdout = "/usr/bin:/bin\n"
        elseif argvHas(cmd, "version") then
          result.stdout = "restic 0.19.1 compiled with go1.26.4 on linux/amd64\n"
        elseif argvHas(cmd, "snapshots") then
          result.exitCode = snapshotExit
          result.stdout = snapshotJson
          result.stderr = snapshotStderr
        elseif argvHas(cmd, "stats") then
          result.stdout = '{"total_size":1024,"total_file_count":7,"snapshots_count":2}\n'
        end
        cb(result)
      end
    end
  end
  return answered
end

local function installRunner()
  runner.pairs = {}
  _G.noctalia.runAsync = function(cmd, cb)
    table.insert(H.commands, cmd)
    table.insert(runner.pairs, { cmd = cmd, cb = cb })
    return true
  end
end

-- Boot the real service on a fresh harness, with optional config/file overrides.
local function boot(config, files, nowMs)
  H.install("plugin/restic-snapshots")
  for key, value in pairs(DEFAULTS) do
    if type(value) == "table" then
      local copy = {}
      for k, v in pairs(value) do
        copy[k] = v
      end
      H.config[key] = copy
    else
      H.config[key] = value
    end
  end
  snapshotJson = "[]"
  snapshotExit = 0
  snapshotStderr = ""
  H.decodeFn = decodeJson
  H.nowMs = nowMs or NOW_MS
  for key, value in pairs(files or {}) do
    H.files[key] = value
  end
  for key, value in pairs(config or {}) do
    H.config[key] = value
  end
  installRunner()
  H.load("service.luau")
  return H
end

-- Restart the service keeping the filesystem it left behind (a shell restart, in one call).
local function restart(config, nowMs)
  local carried = H.files
  H.install("plugin/restic-snapshots")
  H.files = carried
  H.decodeFn = decodeJson
  for key, value in pairs(DEFAULTS) do
    if type(value) == "table" then
      local copy = {}
      for k, v in pairs(value) do
        copy[k] = v
      end
      H.config[key] = copy
    else
      H.config[key] = value
    end
  end
  for key, value in pairs(config or {}) do
    H.config[key] = value
  end
  H.nowMs = nowMs or NOW_MS
  installRunner()
  H.load("service.luau")
end

-- ── introspection ────────────────────────────────────────────────────────────

local function status()
  return H.published["restic_status"]
end

local function jobStarts()
  local count = 0
  for _, cmd in ipairs(H.commands) do
    if cmd[1] == "/bin/sh" then
      count = count + 1
    end
  end
  return count
end

local function argvCalls(needle)
  local count = 0
  for _, cmd in ipairs(H.commands) do
    if argvHas(cmd, needle) then
      count = count + 1
    end
  end
  return count
end

-- Started jobs whose generated script runs a given restic subcommand: precise when the backup
-- and check schedules are both live on the same timeline.
local function jobsRunning(subcommand)
  local count = 0
  for _, cmd in ipairs(H.commands) do
    if cmd[1] == "/bin/sh" then
      local script = H.files[cmd[2]] or ""
      if script:find("'" .. subcommand .. "'", 1, true) ~= nil then
        count = count + 1
      end
    end
  end
  return count
end

-- Every signal sent, in order, as "-TERM 4242" / "-KILL 4242".
local function signals()
  local out = {}
  for _, cmd in ipairs(H.commands) do
    if cmd[1] == "kill" then
      table.insert(out, tostring(cmd[2]) .. " " .. tostring(cmd[3]))
    end
  end
  return out
end

-- The job the service started last, by its generated script, plus the paths the runner wrote to.
local function lastJob()
  for i = #H.commands, 1, -1 do
    local cmd = H.commands[i]
    if cmd[1] == "/bin/sh" and type(cmd[2]) == "string" then
      local token = cmd[2]:match("([^/]+)%.sh$")
      if token ~= nil then
        return token, {
          log = JOB_DIR .. "/" .. token .. ".jsonl",
          status = JOB_DIR .. "/" .. token .. ".status",
          exit = JOB_DIR .. "/" .. token .. ".exit",
          pid = JOB_DIR .. "/" .. token .. ".pid",
          script = cmd[2],
        }
      end
    end
  end
  return nil, nil
end

local function logCount(needle)
  local count = 0
  for _, line in ipairs(H.logs) do
    if line:find(needle, 1, true) ~= nil then
      count = count + 1
    end
  end
  return count
end

local function scriptText()
  local _, paths = lastJob()
  return paths ~= nil and (H.files[paths.script] or "") or ""
end

-- Finish the job in flight the way the runner does: the whole log, then the exit file.
local function exitJob(logText, exitCode)
  local _, paths = lastJob()
  H.files[paths.log] = logText
  H.files[paths.exit] = tostring(exitCode) .. "\n"
  update()
  drain()
end

local function snapshotsJson(entries)
  local parts = {}
  for _, entry in ipairs(entries) do
    table.insert(parts, string.format(
      '{"id":"%s","short_id":"%s","time":"%s","hostname":"cachyos","tags":["noctalia"],'
        .. '"paths":["/tmp/data"],"summary":{"total_files_processed":3,'
        .. '"total_bytes_processed":100,"data_added":10}}',
      entry.id, entry.id:sub(1, 8), entry.time))
  end
  return "[" .. table.concat(parts, ",") .. "]"
end

print("== persistence and catch-up")

do
  -- A previous incarnation left a schedule that is already in the past: the backup it was
  -- waiting to run did not happen, so it has to happen now, not an interval from now.
  local seeded = string.format(
    '{"schema":1,"lastSuccessAt":%d,"nextRunAt":%d,"lastLog":"%s","lastCheckAt":%d,'
      .. '"checkRotationIndex":3,"lastRun":{"at":%d,"ok":true,"exitCode":0,"files":9}}',
    NOW_SEC - 7200, NOW_SEC - 3600, JOB_DIR .. "/oldtoken.jsonl", NOW_SEC - 90000,
    NOW_SEC - 7200)
  boot({ interval_minutes = 60, job_timeout_minutes = 180, check_interval_hours = 0 },
    { [STATE_PATH] = seeded })
  drain()

  local published = status()
  check("the previous run is visible before anything happens",
    published.lastRun ~= nil and published.lastRun.files == 9, published.lastRun and published.lastRun.files)
  check("lastSuccessAt survives a restart", published.lastSuccessAt == NOW_SEC - 7200,
    tostring(published.lastSuccessAt))
  check("a missed run is caught up within a minute",
    published.nextRun ~= nil and published.nextRun >= NOW_SEC and published.nextRun <= NOW_SEC + 60,
    tostring(published.nextRun))
  check("catch-up does not add a whole interval", published.nextRun < NOW_SEC + 3600,
    tostring(published.nextRun))

  local persisted = readState()
  check("the catch-up is written to the store", persisted ~= nil and persisted.nextRunAt == NOW_SEC + 30,
    persisted and tostring(persisted.nextRunAt))

  update()
  check("nothing fires before the catch-up window", jobStarts() == 0, jobStarts())

  H.nowMs = (NOW_SEC + 31) * 1000
  update()
  check("the missed backup fires on catch-up", jobStarts() == 1, jobStarts())
  check("the started job is a backup", scriptText():find("'backup'", 1, true) ~= nil)
  check("starting a catch-up run leaves the rest of the schedule alone",
    status().nextRun == NOW_SEC + 30, tostring(status().nextRun))
end

do
  -- A stored schedule still in the future must be honoured exactly: re-arming from "now" here is
  -- what used to push a backup forward on every restart.
  local seeded = string.format('{"schema":1,"nextRunAt":%d,"lastSuccessAt":%d}',
    NOW_SEC + 1200, NOW_SEC - 600)
  boot({ interval_minutes = 60 }, { [STATE_PATH] = seeded })
  drain()

  check("a stored future run is kept, not recomputed from now", status().nextRun == NOW_SEC + 1200,
    tostring(status().nextRun))

  H.nowMs = (NOW_SEC + 1000) * 1000
  update()
  check("it does not fire early", jobStarts() == 0, jobStarts())

  H.nowMs = (NOW_SEC + 1201) * 1000
  update()
  check("it fires when the stored time arrives", jobStarts() == 1, jobStarts())
end

print("== watchdog")

do
  boot({ interval_minutes = 5, job_timeout_minutes = 1 })
  drain()
  onIpc("backup-now")
  local token, paths = lastJob()
  check("a job is running", token ~= nil and status().busy == true)
  check("jobStartedAt is set while a job runs", status().jobStartedAt == NOW_SEC,
    tostring(status().jobStartedAt))
  H.files[paths.pid] = "4242\n"
  H.files[paths.log] = "indexing files\n"

  H.nowMs = (NOW_SEC + 61) * 1000
  update()
  local sent = signals()
  check("an overrun job is terminated", #sent == 1 and sent[1] == "-TERM 4242",
    table.concat(sent, ", "))
  check("the terminated job is still the only one", jobStarts() == 1, jobStarts())
  check("the watchdog does not invent a finish", status().busy == true)

  -- Measured on restic 0.19.1: it can ignore SIGTERM while uploading, so escalate.
  H.nowMs = (NOW_SEC + 71) * 1000
  update()
  sent = signals()
  check("SIGTERM that is not obeyed escalates to SIGKILL",
    #sent == 2 and sent[2] == "-KILL 4242", table.concat(sent, ", "))

  -- The runner reacts to the kill and writes the exit code it saw; the service must still record
  -- a timeout rather than the code its own signal produced.
  exitJob('{"message_type":"summary","total_files_processed":4}\n', 137)
  check("a timed-out job is not the last run that succeeded", status().lastRun.ok == false)
  check("a timed-out job is recorded with exit code 124", status().lastRun.exitCode == 124,
    tostring(status().lastRun.exitCode))
  check("a timed-out job says so", status().lastRun.error == "timed out", tostring(status().lastRun.error))
  check("a timed-out job is not a cancellation", status().lastRun.cancelled ~= true)
  check("a timed-out job sets status.error", status().error:find("timed out", 1, true) ~= nil,
    status().error)
  check("a timed-out job releases the guard", status().busy == false)
  check("a timed-out job is reported as an error", logCount("error: Restic backup timed out") == 1,
    logCount("error: Restic backup timed out"))
  local joblog = H.published["restic_joblog"]
  check("the timed-out job publishes its log", joblog ~= nil and joblog.kind == "backup"
    and joblog.ok == false and joblog.exitCode == 124, joblog and joblog.kind)

  -- The ceiling is a timeout, not a downtime: the schedule has to keep working.
  local nextAt = status().nextRun
  check("the next run is scheduled after a timeout", nextAt ~= nil and nextAt > NOW_SEC + 71,
    tostring(nextAt))
  H.nowMs = (nextAt + 1) * 1000
  update()
  check("the next scheduled run still fires after a watchdog strike", jobStarts() == 2, jobStarts())
end

do
  -- The signal path must fail closed: a pid file that says 1 (or nothing usable) means the
  -- process cannot be identified, and killing init or a process group is not recoverable.
  boot({ interval_minutes = 5, job_timeout_minutes = 1 })
  drain()
  onIpc("backup-now")
  local _, paths = lastJob()
  H.files[paths.pid] = "1\n"

  H.nowMs = (NOW_SEC + 61) * 1000
  update()
  H.nowMs = (NOW_SEC + 71) * 1000
  update()
  check("a pid of 1 is never signalled", #signals() == 0, table.concat(signals(), ", "))
  check("an unsignalable job stays in flight while the escalation runs", status().busy == true)

  H.nowMs = (NOW_SEC + 82) * 1000
  update()
  check("the guard is released even when no signal could be sent", status().busy == false,
    tostring(status().busy))
  check("the run is still recorded as a timeout", status().lastRun.ok == false
    and status().lastRun.exitCode == 124, tostring(status().lastRun.exitCode))
end

print("== cancel is not failure")

do
  boot({ interval_minutes = 5, job_timeout_minutes = 180 })
  drain()
  onIpc("backup-now")
  local _, paths = lastJob()
  H.files[paths.pid] = "4242\n"
  local errorsBefore = logCount("error: ")

  onIpc("cancel")
  local sent = signals()
  check("cancel signals restic", #sent == 1 and sent[1] == "-TERM 4242", table.concat(sent, ", "))
  check("cancel does not set status.error", status().error == "", status().error)
  check("cancel does not notify an error", logCount("error: ") == errorsBefore)

  exitJob('{"message_type":"summary","total_files_processed":2}\n', 143)
  check("a cancelled run is recorded as cancelled", status().lastRun.cancelled == true)
  check("a cancelled run is not ok", status().lastRun.ok == false)
  check("a cancelled run keeps the exit code it died with", status().lastRun.exitCode == 143,
    tostring(status().lastRun.exitCode))
  check("a cancelled run leaves status.error alone", status().error == "", status().error)
  check("a cancelled run notifies once", logCount("notify: Restic backup cancelled") == 1,
    logCount("notify: Restic backup cancelled"))
  check("a cancelled run releases the guard", status().busy == false)
  check("a cancelled run re-arms the schedule from now",
    status().nextRun == math.floor(H.nowMs / 1000) + 5 * 60, tostring(status().nextRun))

  local persisted = readState()
  check("a cancelled run does not record a success",
    persisted ~= nil and persisted.lastSuccessAt == nil, persisted and tostring(persisted.lastSuccessAt))
  check("a cancelled run is persisted as cancelled",
    persisted ~= nil and persisted.lastRun ~= nil and persisted.lastRun.cancelled == true)
end

print("== failure visibility")

do
  boot({ interval_minutes = 5, job_timeout_minutes = 180 })
  drain()

  onIpc("backup-now")
  -- Two lines; the later one is the more specific reason, so the last error line wins. The text
  -- is what restic 0.19.1 actually prints for a repository that was never initialised (verified
  -- against a scratch repository), which is also what the init detection matches on.
  exitJob('{"message_type":"status","percent_done":0.5}\n'
    .. '{"message_type":"exit_error","code":10,"message":"Fatal: repository does not exist:'
    .. ' unable to open config file: stat /tmp/repo/config: no such file or directory\\n'
    .. 'Is there a repository at the following location?\\n/tmp/repo"}\n', 10)
  check("a failed run sets lastRun.ok to false", status().lastRun.ok == false)
  check("a failed run is not a cancellation", status().lastRun.cancelled ~= true)
  check("a failed run sets status.error from restic's own error line",
    status().error:find("Fatal: repository does not exist", 1, true) == 1, status().error)
  check("a failed run notifies an error", logCount("error: Restic backup failed") == 1)
  check("a failed run publishes a failed log",
    H.published["restic_joblog"].ok == false and H.published["restic_joblog"].exitCode == 10)
  check("a failed run is persisted", readState().lastRun.ok == false)
  check("a run against an uninitialised repository offers to initialise it",
    status().initNeeded == true)

  onIpc("backup-now")
  exitJob('{"message_type":"exit_error","code":1,"message":"Fatal: unable to create lock file: file exists"}\n', 1)
  check("a lock failure says locked so the panel can offer Unlock",
    status().error:lower():find("locked", 1, true) ~= nil, status().error)

  onIpc("backup-now")
  exitJob('{"message_type":"summary","total_files_processed":12,'
    .. '"total_bytes_processed":2048,"data_added":512}\n', 0)
  check("a successful run clears status.error", status().error == "", status().error)
  check("a successful run is recorded ok", status().lastRun.ok == true)
  check("a successful run sets lastSuccessAt", status().lastSuccessAt == math.floor(H.nowMs / 1000),
    tostring(status().lastSuccessAt))
  check("a successful run publishes a readable log", (function()
    local joblog = H.published["restic_joblog"]
    return joblog.lines ~= nil and #joblog.lines == 1 and joblog.truncated == false
  end)())
  check("a successful run refreshes the snapshots", argvCalls("snapshots") >= 2)
end

print("== staleness guardian (observe mode)")

do
  boot({ mode = "observe", interval_minutes = 60, stale_after_hours = 1 })
  snapshotJson = snapshotsJson({ { id = "aaaaaaaa", time = OLD_TIME } })
  drain()

  local published = status()
  check("the repository's newest snapshot is published", published.newestSnapshotAt == 1788838602,
    tostring(published.newestSnapshotAt))
  check("the snapshot count comes from restic", published.snapshotCount == 1)
  check("staleness is measured in hours", published.staleness == 10, tostring(published.staleness))
  check("an old repository is stale", published.stale == true)
  check("going stale notifies once", logCount("error: Restic backup is overdue") == 1,
    logCount("error: Restic backup is overdue"))
  check("observed staleness does not start a backup", jobStarts() == 0, jobStarts())

  -- Same data again: no second warning. The standing rule is one notification per transition.
  onIpc("refresh")
  drain()
  check("staying stale does not notify again", logCount("error: Restic backup is overdue") == 1,
    logCount("error: Restic backup is overdue"))

  snapshotJson = snapshotsJson({ { id = "bbbbbbbb", time = FRESH_TIME } })
  onIpc("refresh")
  drain()
  check("a fresh snapshot is not stale", status().stale == false)
  check("staleness follows the newest snapshot", status().staleness == 1 / 60,
    tostring(status().staleness))
  check("recovery notifies once", logCount("notify: Restic backups are current again") == 1,
    logCount("notify: Restic backups are current again"))

  onIpc("refresh")
  drain()
  check("staying current does not notify again",
    logCount("notify: Restic backups are current again") == 1)

  local persisted = readState()
  check("the newest snapshot is persisted for the widget", persisted.newestSnapshotAt == 1788874542,
    persisted and tostring(persisted.newestSnapshotAt))

  -- A shell restart while the repository is stale must not repeat a warning the user already saw.
  restart({ mode = "observe", interval_minutes = 60, stale_after_hours = 1 })
  snapshotJson = snapshotsJson({ { id = "aaaaaaaa", time = OLD_TIME } })
  drain()
  check("a restart does not repeat a stale warning", logCount("error: Restic backup is overdue") == 1,
    logCount("error: Restic backup is overdue"))
  update()
  check("the restart still knows the repository is stale", status().stale == true)
  check("--no-lock is used for the read-only refresh",
    (function()
      for _, cmd in ipairs(H.commands) do
        if argvHas(cmd, "snapshots") then
          return argvHas(cmd, "--no-lock")
        end
      end
      return false
    end)())
end

print("== an uninitialised repository is a state, not an error")

do
  boot({ interval_minutes = 60 })
  -- What restic 0.19.1 really prints for a repository that was never initialised (verified
  -- against a scratch repository).
  snapshotExit = 10
  snapshotStderr = 'Fatal: repository does not exist: unable to open config file: stat'
    .. ' /tmp/repo/config: no such file or directory\nIs there a repository at the following'
    .. ' location?\n/tmp/repo'
  drain()
  check("an uninitialised repository sets initNeeded", status().initNeeded == true)
  check("an uninitialised repository is not reported as a hard error", status().error == "",
    status().error)
  check("an uninitialised repository is announced once",
    logCount("notify: Restic repository is not initialised yet") == 1,
    logCount("notify: Restic repository is not initialised yet"))

  onIpc("refresh")
  drain()
  check("the initialise prompt is not repeated",
    logCount("notify: Restic repository is not initialised yet") == 1)

  -- Now the repository exists: the refresh after the init must succeed.
  snapshotExit = 0
  snapshotStderr = ""
  onIpc("init")
  exitJob('{"message_type":"initialized","id":"abc","repository":"/tmp/repo"}\n', 0)
  check("a successful init clears initNeeded", status().initNeeded == false)
end

print("== a filtered refresh publishes the filtered view")

do
  boot({ interval_minutes = 60 })
  snapshotJson = snapshotsJson({
    { id = "aaaaaaaa", time = FRESH_TIME },
    { id = "bbbbbbbb", time = FRESH_TIME },
  })
  drain()
  local published = H.published["restic_snapshots"]
  check("an unfiltered refresh publishes every row",
    published ~= nil and #published.snapshots == 2, published and #published.snapshots)

  onIpc("refresh", '{"filter":{"host":"somewhere-else"}}')
  drain()
  local view = H.published["restic_snapshots"]
  check("a filtered refresh publishes only the matching rows", #view.snapshots == 0,
    #view.snapshots)
  check("a filtered refresh still reports the repository truth", status().snapshotCount == 2,
    tostring(status().snapshotCount))
  check("a filtered refresh records the filter it applied",
    view.filter ~= nil and view.filter.host == "somewhere-else")

  onIpc("refresh", '{"filter":{"host":42,"text":""}}')
  drain()
  check("a non-string filter is ignored rather than trusted",
    #H.published["restic_snapshots"].snapshots == 2, #H.published["restic_snapshots"].snapshots)
end

print("== read-only refreshes while a job holds the lock")


do
  boot({ interval_minutes = 5, job_timeout_minutes = 180 })
  drain()
  onIpc("backup-now")
  local before = argvCalls("snapshots")
  local errorsBefore = logCount("error: ")

  onIpc("refresh")
  drain()
  check("a refresh inside a running job is skipped", argvCalls("snapshots") == before,
    argvCalls("snapshots"))
  check("the skip is explained", logCount("error: ") == errorsBefore + 1)
  check("a stats refresh inside a running job is skipped", argvCalls("stats") == 0)

  exitJob('{"message_type":"summary","total_files_processed":1}\n', 0)
  check("read-only refreshes resume once the job is done", argvCalls("snapshots") > before,
    argvCalls("snapshots"))
end

print("== IPC validation")

do
  boot({ interval_minutes = 5, job_timeout_minutes = 180 })
  drain()
  local starts = jobStarts()

  onIpc("forget-one", '{"snapshot":"../../etc/passwd"}')
  check("a flag-shaped snapshot id is refused", jobStarts() == starts, jobStarts())
  check("the refusal names the reason", logCount("restic: rejected forget-one needs a snapshot id") == 1)

  onIpc("forget-one", '{"snapshot":"abcdef12"}')
  check("a valid snapshot id is accepted", jobStarts() == starts + 1, jobStarts())
  check("forget-one never prunes",
    scriptText():find("'--prune'", 1, true) == nil and scriptText():find("'forget'", 1, true) ~= nil)
  check("the password is passed as a file, never as a value",
    scriptText():find("'--password-file'", 1, true) ~= nil
      and scriptText():find("secret", 1, true) == nil)
  exitJob('{"message_type":"summary","files_processed":1}\n', 0)

  starts = jobStarts()
  onIpc("restore", '{"snapshot":"abcdef12","target":"/etc"}')
  check("a restore outside the allow-list is refused", jobStarts() == starts, jobStarts())
  check("the refusal names the allowed roots",
    logCount("restic: rejected restore target must be inside") == 1)

  onIpc("restore", '{"snapshot":"../../etc", "target":"/tmp/restore"}')
  check("a restore with a bad snapshot id is refused", jobStarts() == starts, jobStarts())

  onIpc("diff", '{"from":"zzzzzzzz","to":"abcdef12"}')
  check("a diff with a non-hex id is refused", jobStarts() == starts, jobStarts())

  onIpc("ls", "")
  check("an empty payload is refused", jobStarts() == starts, jobStarts())

  onIpc("no-such-event", "{}")
  check("an unknown event is ignored", jobStarts() == starts and logCount("restic ipc error") == 0)
end

print("== payload shapes")

do
  boot({ interval_minutes = 5, job_timeout_minutes = 180 })
  drain()

  -- retention preview (contract 4.7: kind, at, ok, keepCount, removeCount, remove, truncated)
  onIpc("forget-dry-run")
  check("forget-dry-run starts a dry run",
    scriptText():find("'--dry-run'", 1, true) ~= nil and scriptText():find("'--prune'", 1, true) == nil)
  exitJob('{"keep":[{"id":"aaaa1111","short_id":"aaaa1111","time":"2026-09-08T13:36:42+00:00"}],'
    .. '"remove":[{"id":"bbbb2222","short_id":"bbbb2222","time":"2026-09-08T03:36:42+00:00"}],'
    .. '"reasons":{}}\n', 0)
  local preview = H.published["restic_job"]
  check("the retention preview publishes its shape",
    preview ~= nil and preview.kind == "forget-dry" and preview.ok == true
      and preview.keepCount == 1 and preview.removeCount == 1, preview and preview.kind)
  check("the retention preview lists what would go",
    preview.remove ~= nil and preview.remove[1] ~= nil and preview.remove[1].id == "bbbb2222"
      and preview.remove[1].shortId == "bbbb2222" and preview.remove[1].time ~= nil,
    preview.remove and preview.remove[1] and preview.remove[1].id)
  check("the retention preview is not truncated", preview.truncated == false)

  -- restore preview (contract 4.7: kind, at, ok, snapshot, target, files)
  onIpc("restore-dry-run", '{"snapshot":"abcdef12"}')
  check("the restore preview runs restic restore --dry-run",
    scriptText():find("'restore'", 1, true) ~= nil
      and scriptText():find("'--dry-run'", 1, true) ~= nil
      and scriptText():find("'/tmp/restore'", 1, true) ~= nil)
  exitJob('{"message_type":"summary","total_files":5,"files_restored":5,"total_bytes":2006,'
    .. '"bytes_restored":2006}\n', 0)
  local restored = H.published["restic_job"]
  check("the restore preview publishes its shape",
    restored ~= nil and restored.kind == "restore-dry" and restored.ok == true
      and restored.snapshot == "abcdef12" and restored.target == "/tmp/restore"
      and restored.files == 5, restored and (restored.kind .. " " .. tostring(restored.files)))

  -- the real restore, same guard
  onIpc("restore", '{"snapshot":"abcdef12","target":"/tmp/restore"}')
  check("the real restore is a plain restore",
    scriptText():find("'restore'", 1, true) ~= nil
      and scriptText():find("'--dry-run'", 1, true) == nil)
  exitJob('{"message_type":"summary","total_files":5,"files_restored":5}\n', 0)
  check("a finished restore notifies", logCount("notify: Restore complete") == 1)
  check("a finished restore is persisted", readState().lastRestoreAt ~= nil)

  -- files listing (contract 4.7: snapshot, entries, truncated, at, ok)
  onIpc("ls", '{"snapshot":"abcdef12"}')
  exitJob('{"message_type":"snapshot","id":"abcdef12"}\n'
    .. '{"name":"a.bin","type":"file","path":"/tmp/data/a.bin","size":2000}\n'
    .. '{"name":"sub","type":"dir","path":"/tmp/data/sub"}\n', 0)
  local files = H.published["restic_files"]
  check("the file listing publishes its shape",
    files ~= nil and files.snapshot == "abcdef12" and files.ok == true
      and files.truncated == false and files.at ~= nil, files and files.snapshot)
  check("the file listing carries path, type and size",
    files.entries[1].path == "/tmp/data/a.bin" and files.entries[1].type == "file"
      and files.entries[1].size == 2000,
    files.entries[1] and tostring(files.entries[1].path))

  -- diff (contract 4.7: from, to, added, removed, changed, truncated, at, ok)
  onIpc("diff", '{"from":"11111111","to":"abcdef12"}')
  exitJob('{"message_type":"change","path":"/tmp/data/new.bin","modifier":"+"}\n'
    .. '{"message_type":"change","path":"/tmp/data/gone.bin","modifier":"-"}\n'
    .. '{"message_type":"statistics","changed_files":0}\n', 0)
  local diff = H.published["restic_diff"]
  check("the diff publishes its shape",
    diff ~= nil and diff.from == "11111111" and diff.to == "abcdef12" and diff.ok == true
      and diff.added == 1 and diff.removed == 1 and diff.changed == 0 and diff.truncated == false,
    diff and tostring(diff.added))

  -- repository stats (contract 4.7: totalBytes, totalFileCount, snapshotsCount, updatedAt, ok)
  onIpc("stats")
  drain()
  local stats = H.published["restic_stats"]
  check("the stats card publishes its shape",
    stats ~= nil and stats.totalBytes == 1024 and stats.totalFileCount == 7
      and stats.snapshotsCount == 2 and stats.ok == true and stats.updatedAt ~= nil,
    stats and tostring(stats.totalBytes))

  -- init and unlock
  onIpc("unlock")
  check("unlock asks restic to drop every lock",
    scriptText():find("'unlock'", 1, true) ~= nil
      and scriptText():find("'--remove-all'", 1, true) ~= nil
      and scriptText():find("'--no-lock'", 1, true) == nil)
  exitJob('{"message_type":"summary","removed":1}\n', 0)
  drain()

  onIpc("init")
  check("init runs restic init", scriptText():find("'init'", 1, true) ~= nil)
  exitJob('{"message_type":"initialized","id":"abc","repository":"/tmp/repo"}\n', 0)
  check("a successful init clears initNeeded", status().initNeeded == false)
  check("a successful init notifies", logCount("notify: Restic repository initialised") == 1)

  -- job-log re-publishes the last job's log
  onIpc("job-log")
  local joblog = H.published["restic_joblog"]
  check("job-log republishes the last job's log",
    joblog ~= nil and joblog.kind == "init" and #joblog.lines == 1
      and joblog.lines[1]:find("initialized", 1, true) ~= nil, joblog and joblog.kind)
end

print("== the log viewer survives a restart")

do
  boot({ interval_minutes = 5, job_timeout_minutes = 180 })
  drain()
  onIpc("backup-now")
  local _, paths = lastJob()
  exitJob('{"message_type":"summary","total_files_processed":2}\n', 0)
  local logPath = paths.log
  check("the last log path is persisted", readState().lastLog == logPath, tostring(readState().lastLog))
  local firstLines = H.published["restic_joblog"].lines

  restart({ interval_minutes = 5, job_timeout_minutes = 180 })
  drain()
  check("the persisted log is republished after a restart",
    H.published["restic_joblog"] ~= nil and H.published["restic_joblog"].kind == "backup"
      and H.published["restic_joblog"].lines[1] == firstLines[1],
    H.published["restic_joblog"] and tostring(H.published["restic_joblog"].kind))
  check("the restart still knows the last run", status().lastRun ~= nil and status().lastRun.ok == true)

  H.files[logPath] = nil
  onIpc("job-log")
  check("a re-publish with no log file left publishes an empty log rather than failing",
    H.published["restic_joblog"] ~= nil and #H.published["restic_joblog"].lines == 0
      and logCount("restic ipc error") == 0)
end

print("== scheduled integrity checks")

do
  -- Never checked, interval set: due immediately, reading the first rotating slice. The backup
  -- interval is deliberately long so this timeline measures checks only -- `update()` runs both
  -- schedules and a backup would take the single-job guard first.
  boot({ interval_minutes = 1440, check_interval_hours = 1, check_subset = "1/4" })
  drain()
  update()
  check("a due check starts on the next tick", jobStarts() == 1, jobStarts())
  check("the check reads the first rotating slice",
    scriptText():find("'--read-data-subset=1/4'", 1, true) ~= nil, scriptText())
  check("the check is not a read-only call",
    scriptText():find("'--no-lock'", 1, true) == nil)
  local persisted = readState()
  check("the rotation advances so the next check reads elsewhere",
    persisted ~= nil and persisted.checkRotationIndex == 1, persisted and tostring(persisted.checkRotationIndex))

  exitJob('{"message_type":"summary","num_errors":0}\n', 0)
  local checks = status().checks
  check("the check result is published", checks ~= nil and checks.lastAt ~= nil
    and checks.lastOk == true and checks.numErrors == 0, checks and tostring(checks.lastOk))
  persisted = readState()
  check("the check time is persisted", persisted.lastCheckAt == math.floor(H.nowMs / 1000),
    persisted and tostring(persisted.lastCheckAt))

  update()
  check("a check that just ran is not due again", jobStarts() == 1, jobStarts())
  H.nowMs = (math.floor(H.nowMs / 1000) + 3600 + 1) * 1000
  update()
  check("a check is due after its interval", jobStarts() == 2, jobStarts())
  check("the rotation moves on to the next slice",
    scriptText():find("'--read-data-subset=2/4'", 1, true) ~= nil, scriptText())
  exitJob('{"message_type":"summary","num_errors":3}\n', 0)
  check("check errors are published", status().checks.numErrors == 3,
    tostring(status().checks.numErrors))

  -- Checks off: never run, whatever the clock says.
  boot({ interval_minutes = 1440, check_interval_hours = 0 })
  drain()
  H.nowMs = (NOW_SEC + 30 * 24 * 3600) * 1000
  update()
  check("scheduled checks are off when the interval is 0", jobsRunning("check") == 0, jobsRunning("check"))

  -- A percentage subset has no slots: it must not be turned into a full read.
  boot({ interval_minutes = 1440, check_interval_hours = 1, check_subset = "5%" })
  drain()
  update()
  check("a percentage subset is passed through unchanged",
    scriptText():find("'--read-data-subset=5%'", 1, true) ~= nil, scriptText())
end

print("== scheduled backup re-arms from the last success")

do
  boot({ interval_minutes = 60, job_timeout_minutes = 180 })
  drain()
  H.nowMs = (NOW_SEC - 60) * 1000
  onIpc("backup-now")
  exitJob('{"message_type":"summary","total_files_processed":1}\n', 0)
  check("the next run is a full interval after the success",
    status().nextRun == NOW_SEC - 60 + 3600, tostring(status().nextRun))
  check("the next run is persisted", readState().nextRunAt == NOW_SEC - 60 + 3600,
    tostring(readState().nextRunAt))

  -- An interval change re-derives the schedule and stores it.
  H.config.interval_minutes = 120
  H.nowMs = (NOW_SEC + 60) * 1000
  onConfigChanged()
  drain()
  check("a changed interval re-derives the next run", status().nextRun == NOW_SEC - 60 + 7200,
    tostring(status().nextRun))
  check("the re-derived schedule is persisted", readState().nextRunAt == NOW_SEC - 60 + 7200,
    tostring(readState().nextRunAt))
end

do
  -- The plugin runs its own schedule only in plugin mode.
  boot({ mode = "observe", interval_minutes = 5 })
  drain()
  H.nowMs = (NOW_SEC + 30) * 1000
  update()
  check("observe mode never starts a backup", jobStarts() == 0, jobStarts())
  onIpc("backup-now")
  check("observe mode refuses a manual backup too", jobStarts() == 0, jobStarts())
  check("the refusal is explained", logCount("error: ") == 1)
end

do
  -- A missing repository is reported, not acted on.
  boot({ repository = "" })
  drain()
  onIpc("backup-now")
  check("no repository means no job", jobStarts() == 0, jobStarts())
  onIpc("stats")
  drain()
  check("stats without a repository publishes nothing", H.published["restic_stats"] == nil)
end

print(string.format("\n%s -- %d failure(s)", failures == 0 and "ALL PASS" or "FAILURES", failures))
os.exit(failures == 0 and 0 or 1)
