--!nonstrict
-- Service behaviour tests: plugin/restic-snapshots/service.luau driven for real.
-- Run from the repo root:  lua5.4 tests/lua/service_test.lua
--
-- The service owns the things a backup plugin can get dangerously wrong, so these tests drive
-- the real entry (not a copy of its logic) through the harness and assert on what it published:
--   * a run missed while the shell was off is caught up, and a reload never pushes a backup
--     forward (review finding: "a restart could push a backup forward forever");
--   * a hung restic is struck down, reported as a timeout and cannot block the next run
--     (finding: "a hung restic blocked every future run");
--   * a cancel is a cancel, and a failure is actually visible (finding: "a failed job never set
--     status.error, so a cancel looked exactly like a failure");
--   * a repository that has quietly stopped being backed up is noticed, once, in observe mode
--     too (the feature that would have caught a real missed backup).

package.path = "tests/lua/?.lua;" .. package.path
local H = dofile("tests/lua/harness.lua")

local failures = 0
local function check(name, condition, detail)
  if condition then
    print("ok   " .. name)
  else
    failures = failures + 1
    print("FAIL " .. name .. (detail ~= nil and ("  -- " .. tostring(detail)) or ""))
  end
end

local NOW_MS = 1788874602000
local NOW_SEC = 1788874602
local JOB_DIR = "/tmp/restic-data/jobs"
local STATE_PATH = "/tmp/restic-data/state.json"

-- Timestamps used by the staleness section, in the offset form restic emits.
local OLD_TIME = "2026-09-08T03:36:42+00:00"    -- NOW - 10h  (epoch 1788838602)
local FRESH_TIME = "2026-09-08T13:35:42+00:00"  -- NOW - 60s  (epoch 1788874542)

-- ── a real JSON decoder ──────────────────────────────────────────────────────
-- The store writes state.json and the service reads it back, so "does the schedule survive a
-- restart" cannot be tested against a canned table map: the text is generated by the encoder.

local decodeJson
do
  local function skipSpace(text, pos)
    while true do
      local c = text:sub(pos, pos)
      if c == " " or c == "\t" or c == "\n" or c == "\r" then
        pos = pos + 1
      else
        return pos
      end
    end
  end

  local function parseValue(text, pos)
    pos = skipSpace(text, pos)
    local c = text:sub(pos, pos)
    if c == "{" then
      local out = {}
      pos = skipSpace(text, pos + 1)
      if text:sub(pos, pos) == "}" then
        return out, pos + 1
      end
      while true do
        local key, value
        key, pos = parseValue(text, pos)
        pos = skipSpace(text, pos)
        if text:sub(pos, pos) ~= ":" then
          error("expected : at " .. pos)
        end
        value, pos = parseValue(text, pos + 1)
        if value ~= nil then
          out[key] = value
        end
        pos = skipSpace(text, pos)
        local sep = text:sub(pos, pos)
        if sep == "," then
          pos = pos + 1
        elseif sep == "}" then
          return out, pos + 1
        else
          error("expected , or } at " .. pos)
        end
      end
    elseif c == "[" then
      local out = {}
      pos = skipSpace(text, pos + 1)
      if text:sub(pos, pos) == "]" then
        return out, pos + 1
      end
      while true do
        local value
        value, pos = parseValue(text, pos)
        table.insert(out, value)
        pos = skipSpace(text, pos)
        local sep = text:sub(pos, pos)
        if sep == "," then
          pos = pos + 1
        elseif sep == "]" then
          return out, pos + 1
        else
          error("expected , or ] at " .. pos)
        end
      end
    elseif c == '"' then
      local out = {}
      pos = pos + 1
      while true do
        local ch = text:sub(pos, pos)
        if ch == "" then
          error("unterminated string")
        elseif ch == '"' then
          return table.concat(out), pos + 1
        elseif ch == "\\" then
          local esc = text:sub(pos + 1, pos + 1)
          if esc == "n" then
            table.insert(out, "\n")
          elseif esc == "t" then
            table.insert(out, "\t")
          elseif esc == "r" then
            table.insert(out, "\r")
          elseif esc == "u" then
            table.insert(out, utf8.char(tonumber(text:sub(pos + 2, pos + 5), 16) or 63))
            pos = pos + 4
          elseif esc == "b" then
            table.insert(out, "\b")
          elseif esc == "f" then
            table.insert(out, "\f")
          else
            table.insert(out, esc)
          end
          pos = pos + 2
        else
          table.insert(out, ch)
          pos = pos + 1
        end
      end
    elseif text:sub(pos, pos + 3) == "true" then
      return true, pos + 4
    elseif text:sub(pos, pos + 4) == "false" then
      return false, pos + 5
    elseif text:sub(pos, pos + 3) == "null" then
      return nil, pos + 4
    end
    local stop = pos
    while stop <= #text and text:sub(stop, stop):match("[%d%.eE%+%-]") do
      stop = stop + 1
    end
    local number = tonumber(text:sub(pos, stop - 1))
    if number == nil then
      error("bad value at " .. pos)
    end
    return number, stop
  end

  decodeJson = function(text)
    if type(text) ~= "string" then
      return nil
    end
    local ok, value = pcall(parseValue, text, 1)
    if not ok then
      return nil
    end
    return value
  end
end

local function readState()
  local text = H.files[STATE_PATH]
  if type(text) ~= "string" then
    return nil
  end
  return decodeJson(text)
end

-- ── harness plumbing ─────────────────────────────────────────────────────────

local DEFAULTS = {}
for key, value in pairs(H.config) do
  if type(value) == "table" then
    local copy = {}
    for k, v in pairs(value) do
      copy[k] = v
    end
    DEFAULTS[key] = copy
  else
    DEFAULTS[key] = value
  end
end

-- 0.3.0 settings the harness's canned config predates. H.install() does not reset H.config, so a
-- case that sets one of these would otherwise leak it into every later boot(); seeding them here
-- makes each case start from "unset" like the manifest's default.
DEFAULTS.pre_backup_command = ""
DEFAULTS.post_backup_command = ""
DEFAULTS.metrics_dir = ""
DEFAULTS.verify_interval_hours = 0
DEFAULTS.verify_file_count = 3

local runner = { pairs = {} }
local snapshotJson = "[]"
local snapshotExit = 0
local snapshotStderr = ""

local function argvHas(cmd, needle)
  for _, value in ipairs(cmd) do
    if value == needle then
      return true
    end
  end
  return false
end

-- Answer every read-only runAsync the service issued, classifying it by argv. A callback that
-- issues more work (the login-path probe resolves restic and refreshes) is drained in turn, so a
-- single call settles the service the way a settled shell would.
local function drain()
  local answered = 0
  while #runner.pairs > 0 do
    local batch = runner.pairs
    runner.pairs = {}
    for _, entry in ipairs(batch) do
      local cb = entry.cb
      if cb ~= nil then
        answered = answered + 1
        local cmd = entry.cmd
        local result = { exitCode = 0, stdout = "", stderr = "" }
        if cmd[1] == "sh" then
          result.stdout = "/usr/bin:/bin\n"
        elseif argvHas(cmd, "version") then
          result.stdout = "restic 0.19.1 compiled with go1.26.4 on linux/amd64\n"
        elseif argvHas(cmd, "snapshots") then
          result.exitCode = snapshotExit
          result.stdout = snapshotJson
          result.stderr = snapshotStderr
        elseif argvHas(cmd, "stats") then
          result.stdout = '{"total_size":1024,"total_file_count":7,"snapshots_count":2}\n'
        end
        cb(result)
      end
    end
  end
  return answered
end

local function installRunner()
  runner.pairs = {}
  _G.noctalia.runAsync = function(cmd, cb)
    table.insert(H.commands, cmd)
    table.insert(runner.pairs, { cmd = cmd, cb = cb })
    return true
  end
end

-- Boot the real service on a fresh harness, with optional config/file overrides.
local function boot(config, files, nowMs)
  H.install("plugin/restic-snapshots")
  for key, value in pairs(DEFAULTS) do
    if type(value) == "table" then
      local copy = {}
      for k, v in pairs(value) do
        copy[k] = v
      end
      H.config[key] = copy
    else
      H.config[key] = value
    end
  end
  snapshotJson = "[]"
  snapshotExit = 0
  snapshotStderr = ""
  H.decodeFn = decodeJson
  H.nowMs = nowMs or NOW_MS
  for key, value in pairs(files or {}) do
    H.files[key] = value
  end
  for key, value in pairs(config or {}) do
    H.config[key] = value
  end
  installRunner()
  H.load("service.luau")
  return H
end

-- Restart the service keeping the filesystem it left behind (a shell restart, in one call).
local function restart(config, nowMs)
  local carried = H.files
  H.install("plugin/restic-snapshots")
  H.files = carried
  H.decodeFn = decodeJson
  for key, value in pairs(DEFAULTS) do
    if type(value) == "table" then
      local copy = {}
      for k, v in pairs(value) do
        copy[k] = v
      end
      H.config[key] = copy
    else
      H.config[key] = value
    end
  end
  for key, value in pairs(config or {}) do
    H.config[key] = value
  end
  H.nowMs = nowMs or NOW_MS
  installRunner()
  H.load("service.luau")
end

-- ── introspection ────────────────────────────────────────────────────────────

local function status()
  return H.published["restic_status"]
end

local function jobStarts()
  local count = 0
  for _, cmd in ipairs(H.commands) do
    if cmd[1] == "/bin/sh" then
      count = count + 1
    end
  end
  return count
end

local function argvCalls(needle)
  local count = 0
  for _, cmd in ipairs(H.commands) do
    if argvHas(cmd, needle) then
      count = count + 1
    end
  end
  return count
end

-- Started jobs whose generated script runs a given restic subcommand: precise when the backup
-- and check schedules are both live on the same timeline.
local function jobsRunning(subcommand)
  local count = 0
  for _, cmd in ipairs(H.commands) do
    if cmd[1] == "/bin/sh" then
      local script = H.files[cmd[2]] or ""
      if script:find("'" .. subcommand .. "'", 1, true) ~= nil then
        count = count + 1
      end
    end
  end
  return count
end

-- Every signal sent, in order, as "-TERM 4242" / "-KILL 4242".
local function signals()
  local out = {}
  for _, cmd in ipairs(H.commands) do
    if cmd[1] == "kill" then
      table.insert(out, tostring(cmd[2]) .. " " .. tostring(cmd[3]))
    end
  end
  return out
end

-- The job the service started last, by its generated script, plus the paths the runner wrote to.
local function lastJob()
  for i = #H.commands, 1, -1 do
    local cmd = H.commands[i]
    if cmd[1] == "/bin/sh" and type(cmd[2]) == "string" then
      local token = cmd[2]:match("([^/]+)%.sh$")
      if token ~= nil then
        return token, {
          log = JOB_DIR .. "/" .. token .. ".jsonl",
          status = JOB_DIR .. "/" .. token .. ".status",
          exit = JOB_DIR .. "/" .. token .. ".exit",
          pid = JOB_DIR .. "/" .. token .. ".pid",
          -- [0.3.0] where the script records its own pid; the service signals it first.
          shpid = JOB_DIR .. "/" .. token .. ".shpid",
          script = cmd[2],
        }
      end
    end
  end
  return nil, nil
end

local function logCount(needle)
  local count = 0
  for _, line in ipairs(H.logs) do
    if line:find(needle, 1, true) ~= nil then
      count = count + 1
    end
  end
  return count
end

-- [0.3.0] Metrics export plumbing. The export is written to a temp file and renamed into place, so
-- the write is what proves it ran; the content is read back from the harness's file map.
local METRICS_DIR = "/tmp/noctalia-metrics"
local PROM_PATH = METRICS_DIR .. "/restic_snapshots.prom"

local function metricsWrites()
  local count = 0
  for _, call in ipairs(H.fsCalls) do
    if call.name == "writeFile"
        and tostring(call.path):find("restic_snapshots.prom", 1, true) ~= nil then
      count = count + 1
    end
  end
  return count
end

local function promText()
  return H.files[PROM_PATH] or ""
end

-- [0.4.0] The published job log is metadata plus the log's PATH, and never the log's text
-- (docs/CONTRACTS-0.4.0.md 2.2). `lines`, `display` and `collapsed` were what made the service's
-- update() tick allocate a 97 KB job's worth of tables, and the host killed that callback for it --
-- so the shape is asserted, not just sampled: nothing outside the frozen set may appear.
--
-- A field whose value is nil is an absent key in a Lua table, which is why the running payload is
-- checked as "no key outside the set" (it carries no exitCode because there is no exit code yet --
-- inventing 0 would read as success) while a finished payload is checked as the exact six.
local FROZEN_LOG_KEYS = {
  at = true, cancelled = true, exitCode = true, kind = true, logPath = true, ok = true,
}

local function logPayloadKeys(joblog)
  local keys = {}
  if type(joblog) ~= "table" then
    return keys
  end
  for key in pairs(joblog) do
    table.insert(keys, tostring(key))
  end
  table.sort(keys)
  return keys
end

-- The payload publishes a reference: where the log is, the run's own metadata, and nothing of the
-- log itself -- whatever the run is doing.
local function noLogBody(label, joblog)
  local extra = {}
  for _, key in ipairs(logPayloadKeys(joblog)) do
    if FROZEN_LOG_KEYS[key] ~= true then
      table.insert(extra, key)
    end
  end
  check(label .. ": the payload carries only the frozen metadata keys, and no log text",
    type(joblog) == "table" and #extra == 0 and type(joblog.logPath) == "string"
      and joblog.lines == nil and joblog.display == nil and joblog.collapsed == nil,
    "extra=" .. table.concat(extra, ",") .. " keys=" .. table.concat(logPayloadKeys(joblog), ","))
end

-- A finished payload carries all six: kind, when, ok, cancelled, exitCode and the log's path.
local function fullLogPayload(label, joblog)
  check(label .. ": the payload is the full frozen shape",
    table.concat(logPayloadKeys(joblog), ",") == "at,cancelled,exitCode,kind,logPath,ok",
    table.concat(logPayloadKeys(joblog), ","))
end

-- Does the log the published payload POINTS AT contain `needle`? The payload no longer carries the
-- text, so this reads the file through the same host call the panel reads it with.
local function logHas(needle)
  local joblog = H.published["restic_joblog"]
  local path = type(joblog) == "table" and joblog.logPath or nil
  if type(path) ~= "string" then
    return false
  end
  local text = noctalia.readFile(path)
  return type(text) == "string" and text:find(needle, 1, true) ~= nil
end

local function scriptText()
  local _, paths = lastJob()
  return paths ~= nil and (H.files[paths.script] or "") or ""
end

-- [0.4.0] The real restic 0.19.1 captures, read from disk: a job log is precisely the thing that
-- must be tested against what restic writes, not against JSON someone typed by hand. The paths are
-- relative to the repo root, which is where the gate runs this suite from.
local function readFixture(name)
  local handle = io.open("tests/fixtures/" .. name, "r")
  if handle == nil then
    check("fixture " .. name .. " is readable", false, "tests/fixtures/" .. name .. " is missing")
    return ""
  end
  local text = handle:read("a")
  handle:close()
  return text
end

-- Finish the job in flight the way the runner does: the whole log, then the exit file.
local function exitJob(logText, exitCode)
  local _, paths = lastJob()
  H.files[paths.log] = logText
  H.files[paths.exit] = tostring(exitCode) .. "\n"
  update()
  drain()
end

local function snapshotsJson(entries)
  local parts = {}
  for _, entry in ipairs(entries) do
    table.insert(parts, string.format(
      '{"id":"%s","short_id":"%s","time":"%s","hostname":"cachyos","tags":["noctalia"],'
        .. '"paths":["/tmp/data"],"summary":{"total_files_processed":3,'
        .. '"total_bytes_processed":100,"data_added":10}}',
      entry.id, entry.id:sub(1, 8), entry.time))
  end
  return "[" .. table.concat(parts, ",") .. "]"
end

print("== persistence and catch-up")

do
  -- A previous incarnation left a schedule that is already in the past: the backup it was
  -- waiting to run did not happen, so it has to happen now, not an interval from now.
  local seeded = string.format(
    '{"schema":1,"lastSuccessAt":%d,"nextRunAt":%d,"lastLog":"%s","lastCheckAt":%d,'
      .. '"checkRotationIndex":3,"lastRun":{"at":%d,"ok":true,"exitCode":0,"files":9}}',
    NOW_SEC - 7200, NOW_SEC - 3600, JOB_DIR .. "/oldtoken.jsonl", NOW_SEC - 90000,
    NOW_SEC - 7200)
  boot({ interval_minutes = 60, job_timeout_minutes = 180, check_interval_hours = 0 },
    { [STATE_PATH] = seeded })
  drain()

  local published = status()
  check("the previous run is visible before anything happens",
    published.lastRun ~= nil and published.lastRun.files == 9, published.lastRun and published.lastRun.files)
  check("lastSuccessAt survives a restart", published.lastSuccessAt == NOW_SEC - 7200,
    tostring(published.lastSuccessAt))
  check("a missed run is caught up within a minute",
    published.nextRun ~= nil and published.nextRun >= NOW_SEC and published.nextRun <= NOW_SEC + 60,
    tostring(published.nextRun))
  check("catch-up does not add a whole interval", published.nextRun < NOW_SEC + 3600,
    tostring(published.nextRun))

  local persisted = readState()
  check("the catch-up is written to the store", persisted ~= nil and persisted.nextRunAt == NOW_SEC + 30,
    persisted and tostring(persisted.nextRunAt))

  update()
  check("nothing fires before the catch-up window", jobStarts() == 0, jobStarts())

  H.nowMs = (NOW_SEC + 31) * 1000
  update()
  check("the missed backup fires on catch-up", jobStarts() == 1, jobStarts())
  check("the started job is a backup", scriptText():find("'backup'", 1, true) ~= nil)
  check("starting a catch-up run leaves the rest of the schedule alone",
    status().nextRun == NOW_SEC + 30, tostring(status().nextRun))
end

do
  -- A stored schedule still in the future must be honoured exactly: re-arming from "now" here is
  -- what used to push a backup forward on every restart.
  local seeded = string.format('{"schema":1,"nextRunAt":%d,"lastSuccessAt":%d}',
    NOW_SEC + 1200, NOW_SEC - 600)
  boot({ interval_minutes = 60 }, { [STATE_PATH] = seeded })
  drain()

  check("a stored future run is kept, not recomputed from now", status().nextRun == NOW_SEC + 1200,
    tostring(status().nextRun))

  H.nowMs = (NOW_SEC + 1000) * 1000
  update()
  check("it does not fire early", jobStarts() == 0, jobStarts())

  H.nowMs = (NOW_SEC + 1201) * 1000
  update()
  check("it fires when the stored time arrives", jobStarts() == 1, jobStarts())
end

print("== watchdog")

do
  boot({ interval_minutes = 5, job_timeout_minutes = 1 })
  drain()
  onIpc("backup-now")
  local token, paths = lastJob()
  check("a job is running", token ~= nil and status().busy == true)
  check("jobStartedAt is set while a job runs", status().jobStartedAt == NOW_SEC,
    tostring(status().jobStartedAt))
  H.files[paths.pid] = "4242\n"
  H.files[paths.log] = "indexing files\n"

  H.nowMs = (NOW_SEC + 61) * 1000
  update()
  local sent = signals()
  check("an overrun job is terminated", #sent == 1 and sent[1] == "-TERM 4242",
    table.concat(sent, ", "))
  check("the terminated job is still the only one", jobStarts() == 1, jobStarts())
  check("the watchdog does not invent a finish", status().busy == true)

  -- Measured on restic 0.19.1: it can ignore SIGTERM while uploading, so escalate.
  H.nowMs = (NOW_SEC + 71) * 1000
  update()
  sent = signals()
  check("SIGTERM that is not obeyed escalates to SIGKILL",
    #sent == 2 and sent[2] == "-KILL 4242", table.concat(sent, ", "))

  -- The runner reacts to the kill and writes the exit code it saw; the service must still record
  -- a timeout rather than the code its own signal produced.
  exitJob('{"message_type":"summary","total_files_processed":4}\n', 137)
  check("a timed-out job is not the last run that succeeded", status().lastRun.ok == false)
  check("a timed-out job is recorded with exit code 124", status().lastRun.exitCode == 124,
    tostring(status().lastRun.exitCode))
  check("a timed-out job says so", status().lastRun.error == "timed out", tostring(status().lastRun.error))
  check("a timed-out job is not a cancellation", status().lastRun.cancelled ~= true)
  check("a timed-out job sets status.error", status().error:find("timed out", 1, true) ~= nil,
    status().error)
  check("a timed-out job releases the guard", status().busy == false)
  check("a timed-out job is reported as an error", logCount("error: Restic backup timed out") == 1,
    logCount("error: Restic backup timed out"))
  local joblog = H.published["restic_joblog"]
  check("the timed-out job publishes its log reference",
    joblog ~= nil and joblog.kind == "backup" and joblog.ok == false
      and joblog.exitCode == 124 and joblog.logPath == paths.log,
    joblog and tostring(joblog.logPath))
  noLogBody("a timed-out job", joblog)
  fullLogPayload("a timed-out job", joblog)

  -- The ceiling is a timeout, not a downtime: the schedule has to keep working.
  local nextAt = status().nextRun
  check("the next run is scheduled after a timeout", nextAt ~= nil and nextAt > NOW_SEC + 71,
    tostring(nextAt))
  H.nowMs = (nextAt + 1) * 1000
  update()
  check("the next scheduled run still fires after a watchdog strike", jobStarts() == 2, jobStarts())
end

do
  -- The signal path must fail closed: a pid file that says 1 (or nothing usable) means the
  -- process cannot be identified, and killing init or a process group is not recoverable.
  boot({ interval_minutes = 5, job_timeout_minutes = 1 })
  drain()
  onIpc("backup-now")
  local _, paths = lastJob()
  H.files[paths.pid] = "1\n"

  H.nowMs = (NOW_SEC + 61) * 1000
  update()
  H.nowMs = (NOW_SEC + 71) * 1000
  update()
  check("a pid of 1 is never signalled", #signals() == 0, table.concat(signals(), ", "))
  check("an unsignalable job stays in flight while the escalation runs", status().busy == true)

  H.nowMs = (NOW_SEC + 82) * 1000
  update()
  check("the guard is released even when no signal could be sent", status().busy == false,
    tostring(status().busy))
  check("the run is still recorded as a timeout", status().lastRun.ok == false
    and status().lastRun.exitCode == 124, tostring(status().lastRun.exitCode))
end

print("== cancel is not failure")

do
  boot({ interval_minutes = 5, job_timeout_minutes = 180 })
  drain()
  onIpc("backup-now")
  local _, paths = lastJob()
  H.files[paths.pid] = "4242\n"
  local errorsBefore = logCount("error: ")

  onIpc("cancel")
  local sent = signals()
  check("cancel signals restic", #sent == 1 and sent[1] == "-TERM 4242", table.concat(sent, ", "))
  check("cancel does not set status.error", status().error == "", status().error)
  check("cancel does not notify an error", logCount("error: ") == errorsBefore)

  exitJob('{"message_type":"summary","total_files_processed":2}\n', 143)
  check("a cancelled run is recorded as cancelled", status().lastRun.cancelled == true)
  check("a cancelled run is not ok", status().lastRun.ok == false)
  check("a cancelled run keeps the exit code it died with", status().lastRun.exitCode == 143,
    tostring(status().lastRun.exitCode))
  check("a cancelled run leaves status.error alone", status().error == "", status().error)
  check("a cancelled run notifies once", logCount("notify: Restic backup cancelled") == 1,
    logCount("notify: Restic backup cancelled"))
  check("a cancelled run releases the guard", status().busy == false)
  check("a cancelled run re-arms the schedule from now",
    status().nextRun == math.floor(H.nowMs / 1000) + 5 * 60, tostring(status().nextRun))

  local persisted = readState()
  check("a cancelled run does not record a success",
    persisted ~= nil and persisted.lastSuccessAt == nil, persisted and tostring(persisted.lastSuccessAt))
  check("a cancelled run is persisted as cancelled",
    persisted ~= nil and persisted.lastRun ~= nil and persisted.lastRun.cancelled == true)
end

print("== cancel reaches the job script, not only restic")

do
  -- Both pids exist: restic is up and the script has recorded its own pid too.
  boot({ interval_minutes = 5, job_timeout_minutes = 1 })
  drain()
  onIpc("backup-now")
  local _, paths = lastJob()
  H.files[paths.pid] = "9999\n"
  H.files[paths.shpid] = "4242\n"

  onIpc("cancel")
  local sent = signals()
  check("cancel signals the job script, not restic", #sent == 1 and sent[1] == "-TERM 4242",
    table.concat(sent, ", "))

  -- The watchdog's escalation has to reach the same process, or a job the script's trap missed
  -- would be killable only in restic's name.
  H.nowMs = (NOW_SEC + 61) * 1000
  update()
  H.nowMs = (NOW_SEC + 71) * 1000
  update()
  sent = signals()
  check("the watchdog escalates to KILL on the script pid too",
    #sent == 2 and sent[2] == "-KILL 4242", table.concat(sent, ", "))
  exitJob('{"message_type":"summary"}\n', 143)
end

do
  -- The hole itself: a pre-command is running, so restic has not started and there is no restic
  -- pid file at all. Before 0.3.0 cancel did nothing here, and a watchdog strike released the
  -- single-flight guard while the script - and its hook - kept running.
  boot({ interval_minutes = 5, job_timeout_minutes = 180, pre_backup_command = "sleep 60" })
  drain()
  onIpc("backup-now")
  local _, paths = lastJob()
  H.files[paths.pid] = nil
  H.files[paths.shpid] = "4242\n"

  onIpc("cancel")
  local sent = signals()
  check("cancel reaches a job whose pre-command is still running",
    #sent == 1 and sent[1] == "-TERM 4242", table.concat(sent, ", "))
  check("the script's trap is the only pid a hook job has recorded",
    H.files[paths.pid] == nil and H.files[paths.shpid] == "4242\n")

  -- What the trap leaves behind: the job ends with 143 and the service records a cancel.
  exitJob("== pre-backup command ==\n", 143)
  check("the cancelled hook job is recorded as cancelled", status().lastRun.cancelled == true)
  check("the cancelled hook job is not a restic failure", status().error == "", status().error)
  check("the cancelled hook job releases the guard", status().busy == false)
end

print("== failure visibility")

do
  boot({ interval_minutes = 5, job_timeout_minutes = 180 })
  drain()

  onIpc("backup-now")
  -- Two lines; the later one is the more specific reason, so the last error line wins. The text
  -- is what restic 0.19.1 actually prints for a repository that was never initialised (verified
  -- against a scratch repository), which is also what the init detection matches on.
  exitJob('{"message_type":"status","percent_done":0.5}\n'
    .. '{"message_type":"exit_error","code":10,"message":"Fatal: repository does not exist:'
    .. ' unable to open config file: stat /tmp/repo/config: no such file or directory\\n'
    .. 'Is there a repository at the following location?\\n/tmp/repo"}\n', 10)
  check("a failed run sets lastRun.ok to false", status().lastRun.ok == false)
  check("a failed run is not a cancellation", status().lastRun.cancelled ~= true)
  check("a failed run sets status.error from restic's own error line",
    status().error:find("Fatal: repository does not exist", 1, true) == 1, status().error)
  check("a failed run notifies an error", logCount("error: Restic backup failed") == 1)
  check("a failed run publishes a failed log",
    H.published["restic_joblog"].ok == false and H.published["restic_joblog"].exitCode == 10)
  check("a failed run is persisted", readState().lastRun.ok == false)
  check("a run against an uninitialised repository offers to initialise it",
    status().initNeeded == true)

  onIpc("backup-now")
  exitJob('{"message_type":"exit_error","code":1,"message":"Fatal: unable to create lock file: file exists"}\n', 1)
  check("a lock failure says locked so the panel can offer Unlock",
    status().error:lower():find("locked", 1, true) ~= nil, status().error)

  onIpc("backup-now")
  local _, successPaths = lastJob()
  local summaryText = '{"message_type":"summary","total_files_processed":12,'
    .. '"total_bytes_processed":2048,"data_added":512}\n'
  exitJob(summaryText, 0)
  check("a successful run clears status.error", status().error == "", status().error)
  check("a successful run is recorded ok", status().lastRun.ok == true)
  check("a successful run sets lastSuccessAt", status().lastSuccessAt == math.floor(H.nowMs / 1000),
    tostring(status().lastSuccessAt))
  check("a successful run publishes a readable log", (function()
    local joblog = H.published["restic_joblog"]
    return joblog ~= nil and joblog.logPath == successPaths.log
      and noctalia.readFile(joblog.logPath) == summaryText
  end)())
  noLogBody("a successful run", H.published["restic_joblog"])
  fullLogPayload("a successful run", H.published["restic_joblog"])
  check("a successful run refreshes the snapshots", argvCalls("snapshots") >= 2)
end

print("== pre/post-backup hooks reach the backup path and nothing else")

do
  boot({
    interval_minutes = 1440,
    check_interval_hours = 1,
    pre_backup_command = "dump --to /tmp/stage",
    post_backup_command = "sync --done",
  })
  drain()

  onIpc("backup-now")
  local backup = scriptText()
  check("a configured pre-command reaches the generated script",
    backup:find("PRECOMMAND='dump --to /tmp/stage'", 1, true) ~= nil,
    backup:sub(1, 200))
  check("a configured post-command reaches the generated script",
    backup:find("POSTCOMMAND='sync --done'", 1, true) ~= nil)
  check("the pre-command is invoked before restic and the post-command after it",
    (backup:find("sh -c \"$PRECOMMAND\"", 1, true) or 0) < (backup:find("'backup'", 1, true) or 0)
      and (backup:find("sh -c \"$POSTCOMMAND\"", 1, true) or 0) > (backup:find("'backup'", 1, true) or 0))
  exitJob('{"message_type":"summary","total_files_processed":1}\n', 0)

  -- The settings are named pre/post-*backup*: no other job kind may run them.
  onIpc("check")
  local checkScript = scriptText()
  check("a check job's script carries no pre-command",
    checkScript:find("PRECOMMAND", 1, true) == nil, checkScript:sub(1, 200))
  check("a check job's script carries no post-command",
    checkScript:find("POSTCOMMAND", 1, true) == nil)
  check("a check job's script has no hook invocation at all",
    checkScript:find("/bin/sh -c", 1, true) == nil)
  exitJob('{"message_type":"summary","num_errors":0}\n', 0)

  -- A restore must not run them either - the settings belong to the backup.
  onIpc("restore-dry-run", '{"snapshot":"abcdef12"}')
  check("a restore job's script carries no hooks",
    scriptText():find("PRECOMMAND", 1, true) == nil
      and scriptText():find("POSTCOMMAND", 1, true) == nil)
  exitJob('{"message_type":"summary","total_files":1,"files_restored":1}\n', 0)

  -- The defaults: an empty setting is no hook, so a hook-free job is generated exactly as before.
  boot({ interval_minutes = 1440, pre_backup_command = "", post_backup_command = "" })
  drain()
  onIpc("backup-now")
  check("an empty pre-command setting generates no hook",
    scriptText():find("PRECOMMAND", 1, true) == nil
      and scriptText():find("PRE_", 1, true) == nil)
  check("an empty post-command setting generates no hook",
    scriptText():find("POSTCOMMAND", 1, true) == nil)
  check("the hook-free script still has the cancellation machinery",
    scriptText():find('> "$shpidfile"', 1, true) ~= nil
      and scriptText():find(" TERM INT HUP", 1, true) ~= nil)
  exitJob('{"message_type":"summary","total_files_processed":1}\n', 0)
end

print("== a failing pre-command is reported honestly")

do
  boot({ interval_minutes = 1440, pre_backup_command = "exit 3" })
  drain()
  onIpc("backup-now")
  check("a backup with a pre-command is started", jobStarts() == 1, jobStarts())
  -- Exactly what the runner writes when the pre-command aborts the job: the marker, the hook's own
  -- output, and the runner's line saying restic was never started. The exit code is the hook's.
  exitJob("== pre-backup command ==\nboom: the staging dump failed\n"
    .. "the pre-backup command failed; restic was not started\n", 3)

  local published = status()
  check("a failing pre-command is not a success", published.lastRun.ok == false)
  check("a failing pre-command is not a cancellation", published.lastRun.cancelled ~= true)
  check("the recorded exit code is the hook's", published.lastRun.exitCode == 3,
    tostring(published.lastRun.exitCode))
  check("the error does not claim restic failed",
    published.error:find("restic was not started", 1, true) ~= nil
      and published.error:find("backup failed", 1, true) == nil, published.error)
  check("a failing pre-command is not announced as a restic failure",
    logCount("error: Restic backup failed") == 0, logCount("error: Restic backup failed"))
  check("a failing pre-command is announced for what it is",
    logCount("error: Restic pre-backup command failed") == 1,
    logCount("error: Restic pre-backup command failed"))
  local joblog = H.published["restic_joblog"]
  check("the job log is published as failed",
    joblog ~= nil and joblog.ok == false and joblog.exitCode == 3,
    joblog and tostring(joblog.ok))
  check("the published log shows the pre-command marker", logHas("== pre-backup command =="))
  check("the published log shows the hook's own output", logHas("boom: the staging dump failed"))
  check("the published log says restic was never started", logHas("restic was not started"))
  check("the run is persisted as failed", readState().lastRun.ok == false)
  check("a failing pre-command does not record a success", published.lastSuccessAt == nil,
    tostring(published.lastSuccessAt))
  check("a failing pre-command releases the guard", published.busy == false)
end

print("== metrics export")

do
  -- The feature unset: nothing under the metrics path is written or even looked at.
  boot({ interval_minutes = 1440, metrics_dir = "" })
  drain()
  onIpc("backup-now")
  exitJob('{"message_type":"summary","total_files_processed":1}\n', 0)
  check("with no metrics directory nothing is written", H.files[PROM_PATH] == nil)
  check("with no metrics directory no write is attempted", metricsWrites() == 0, metricsWrites())
end

do
  -- Configured: the config load itself is a transition, and a job finish is another.
  boot({ interval_minutes = 1440, metrics_dir = METRICS_DIR })
  drain()
  check("loading the config writes the export", metricsWrites() >= 1 and H.files[PROM_PATH] ~= nil,
    metricsWrites())

  onIpc("backup-now")
  local before = metricsWrites()
  exitJob('{"message_type":"summary","total_files_processed":4,"total_bytes_processed":2048,'
    .. '"data_added":512}\n', 0)
  drain()
  check("a finished job rewrites the export", metricsWrites() > before,
    metricsWrites() .. " vs " .. before)

  local text = promText()
  check("the export records the last job's kind and exit code",
    text:find('restic_snapshots_last_job_exit_code{kind="backup"} 0', 1, true) ~= nil, text)
  check("the export records when the backup succeeded",
    text:find("restic_snapshots_last_success_timestamp_seconds " .. tostring(NOW_SEC), 1, true) ~= nil,
    text)
  check("the export carries the repository's snapshot count",
    text:find("restic_snapshots_count ", 1, true) ~= nil, text)
  check("the export dates itself", text:find("restic_snapshots_export_timestamp_seconds", 1, true) ~= nil)
  check("the export is published atomically", (function()
    for _, call in ipairs(H.fsCalls) do
      if call.name == "renameFile" and tostring(call.to) == PROM_PATH then
        return true
      end
    end
    return false
  end)())

  -- The tick is not a transition. A write from update() would re-stamp the file every couple of
  -- seconds and make the export's own timestamp meaningless.
  local afterJob = metricsWrites()
  H.nowMs = (NOW_SEC + 120) * 1000
  update()
  update()
  drain()
  check("the update tick never rewrites the export", metricsWrites() == afterJob, metricsWrites())

  -- A refresh is a transition, and so is a verification attempt.
  H.nowMs = (NOW_SEC + 130) * 1000
  onIpc("refresh")
  drain()
  check("a snapshot refresh rewrites the export", metricsWrites() > afterJob, metricsWrites())
end

do
  -- A failing write: one log line per failure streak, and never a mark on the job that caused it.
  boot({ interval_minutes = 1440, metrics_dir = METRICS_DIR })
  drain()
  onIpc("backup-now")
  -- From here every filesystem write fails - the generated script is already on disk, so only the
  -- export and the state file are affected.
  H.failCalls.writeFile = true
  exitJob('{"message_type":"summary","total_files_processed":2}\n', 0)
  drain()
  check("a failing export is logged once", logCount("restic: metrics export failed") == 1,
    logCount("restic: metrics export failed"))
  check("a failing export does not change the job's result", status().lastRun.ok == true,
    tostring(status().lastRun.ok))
  check("a failing export does not set status.error", status().error == "", status().error)

  H.nowMs = (NOW_SEC + 60) * 1000
  onIpc("refresh")
  drain()
  onIpc("refresh")
  drain()
  check("further failed exports do not fill the log",
    logCount("restic: metrics export failed") == 1, logCount("restic: metrics export failed"))

  -- A successful write re-arms the line, so a later failure is still visible.
  H.failCalls.writeFile = false
  onIpc("refresh")
  drain()
  H.failCalls.writeFile = true
  onIpc("refresh")
  drain()
  check("a failure after a recovery is logged again",
    logCount("restic: metrics export failed") == 2, logCount("restic: metrics export failed"))
end

print("== staleness guardian (observe mode)")

do
  boot({ mode = "observe", interval_minutes = 60, stale_after_hours = 1 })
  snapshotJson = snapshotsJson({ { id = "aaaaaaaa", time = OLD_TIME } })
  drain()

  local published = status()
  check("the repository's newest snapshot is published", published.newestSnapshotAt == 1788838602,
    tostring(published.newestSnapshotAt))
  check("the snapshot count comes from restic", published.snapshotCount == 1)
  check("staleness is measured in hours", published.staleness == 10, tostring(published.staleness))
  check("an old repository is stale", published.stale == true)
  check("going stale notifies once", logCount("error: Restic backup is overdue") == 1,
    logCount("error: Restic backup is overdue"))
  check("observed staleness does not start a backup", jobStarts() == 0, jobStarts())

  -- Same data again: no second warning. The standing rule is one notification per transition.
  onIpc("refresh")
  drain()
  check("staying stale does not notify again", logCount("error: Restic backup is overdue") == 1,
    logCount("error: Restic backup is overdue"))

  snapshotJson = snapshotsJson({ { id = "bbbbbbbb", time = FRESH_TIME } })
  onIpc("refresh")
  drain()
  check("a fresh snapshot is not stale", status().stale == false)
  check("staleness follows the newest snapshot", status().staleness == 1 / 60,
    tostring(status().staleness))
  check("recovery notifies once", logCount("notify: Restic backups are current again") == 1,
    logCount("notify: Restic backups are current again"))

  onIpc("refresh")
  drain()
  check("staying current does not notify again",
    logCount("notify: Restic backups are current again") == 1)

  local persisted = readState()
  check("the newest snapshot is persisted for the widget", persisted.newestSnapshotAt == 1788874542,
    persisted and tostring(persisted.newestSnapshotAt))

  -- A shell restart while the repository is stale must not repeat a warning the user already saw.
  restart({ mode = "observe", interval_minutes = 60, stale_after_hours = 1 })
  snapshotJson = snapshotsJson({ { id = "aaaaaaaa", time = OLD_TIME } })
  drain()
  check("a restart does not repeat a stale warning", logCount("error: Restic backup is overdue") == 1,
    logCount("error: Restic backup is overdue"))
  update()
  check("the restart still knows the repository is stale", status().stale == true)
  check("--no-lock is used for the read-only refresh",
    (function()
      for _, cmd in ipairs(H.commands) do
        if argvHas(cmd, "snapshots") then
          return argvHas(cmd, "--no-lock")
        end
      end
      return false
    end)())
end

print("== an uninitialised repository is a state, not an error")

do
  boot({ interval_minutes = 60 })
  -- What restic 0.19.1 really prints for a repository that was never initialised (verified
  -- against a scratch repository).
  snapshotExit = 10
  snapshotStderr = 'Fatal: repository does not exist: unable to open config file: stat'
    .. ' /tmp/repo/config: no such file or directory\nIs there a repository at the following'
    .. ' location?\n/tmp/repo'
  drain()
  check("an uninitialised repository sets initNeeded", status().initNeeded == true)
  check("an uninitialised repository is not reported as a hard error", status().error == "",
    status().error)
  check("an uninitialised repository is announced once",
    logCount("notify: Restic repository is not initialised yet") == 1,
    logCount("notify: Restic repository is not initialised yet"))

  onIpc("refresh")
  drain()
  check("the initialise prompt is not repeated",
    logCount("notify: Restic repository is not initialised yet") == 1)

  -- Now the repository exists: the refresh after the init must succeed.
  snapshotExit = 0
  snapshotStderr = ""
  onIpc("init")
  exitJob('{"message_type":"initialized","id":"abc","repository":"/tmp/repo"}\n', 0)
  check("a successful init clears initNeeded", status().initNeeded == false)
end

print("== a filtered refresh publishes the filtered view")

do
  boot({ interval_minutes = 60 })
  snapshotJson = snapshotsJson({
    { id = "aaaaaaaa", time = FRESH_TIME },
    { id = "bbbbbbbb", time = FRESH_TIME },
  })
  drain()
  local published = H.published["restic_snapshots"]
  check("an unfiltered refresh publishes every row",
    published ~= nil and #published.snapshots == 2, published and #published.snapshots)

  onIpc("refresh", '{"filter":{"host":"somewhere-else"}}')
  drain()
  local view = H.published["restic_snapshots"]
  check("a filtered refresh publishes only the matching rows", #view.snapshots == 0,
    #view.snapshots)
  check("a filtered refresh still reports the repository truth", status().snapshotCount == 2,
    tostring(status().snapshotCount))
  check("a filtered refresh records the filter it applied",
    view.filter ~= nil and view.filter.host == "somewhere-else")

  onIpc("refresh", '{"filter":{"host":42,"text":""}}')
  drain()
  check("a non-string filter is ignored rather than trusted",
    #H.published["restic_snapshots"].snapshots == 2, #H.published["restic_snapshots"].snapshots)
end

print("== read-only refreshes while a job holds the lock")


do
  boot({ interval_minutes = 5, job_timeout_minutes = 180 })
  drain()
  onIpc("backup-now")
  local before = argvCalls("snapshots")
  local errorsBefore = logCount("error: ")

  onIpc("refresh")
  drain()
  check("a refresh inside a running job is skipped", argvCalls("snapshots") == before,
    argvCalls("snapshots"))
  check("the skip is explained", logCount("error: ") == errorsBefore + 1)
  check("a stats refresh inside a running job is skipped", argvCalls("stats") == 0)

  exitJob('{"message_type":"summary","total_files_processed":1}\n', 0)
  check("read-only refreshes resume once the job is done", argvCalls("snapshots") > before,
    argvCalls("snapshots"))
end

print("== IPC validation")

do
  boot({ interval_minutes = 5, job_timeout_minutes = 180 })
  drain()
  local starts = jobStarts()

  onIpc("forget-one", '{"snapshot":"../../etc/passwd"}')
  check("a flag-shaped snapshot id is refused", jobStarts() == starts, jobStarts())
  check("the refusal names the reason", logCount("restic: rejected forget-one needs a snapshot id") == 1)

  onIpc("forget-one", '{"snapshot":"abcdef12"}')
  check("a valid snapshot id is accepted", jobStarts() == starts + 1, jobStarts())
  check("forget-one never prunes",
    scriptText():find("'--prune'", 1, true) == nil and scriptText():find("'forget'", 1, true) ~= nil)
  check("the password is passed as a file, never as a value",
    scriptText():find("'--password-file'", 1, true) ~= nil
      and scriptText():find("secret", 1, true) == nil)
  exitJob('{"message_type":"summary","files_processed":1}\n', 0)

  starts = jobStarts()
  onIpc("restore", '{"snapshot":"abcdef12","target":"/etc"}')
  check("a restore outside the allow-list is refused", jobStarts() == starts, jobStarts())
  check("the refusal names the allowed roots",
    logCount("restic: rejected restore target must be inside") == 1)

  onIpc("restore", '{"snapshot":"../../etc", "target":"/tmp/restore"}')
  check("a restore with a bad snapshot id is refused", jobStarts() == starts, jobStarts())

  onIpc("diff", '{"from":"zzzzzzzz","to":"abcdef12"}')
  check("a diff with a non-hex id is refused", jobStarts() == starts, jobStarts())

  onIpc("ls", "")
  check("an empty payload is refused", jobStarts() == starts, jobStarts())

  onIpc("no-such-event", "{}")
  check("an unknown event is ignored", jobStarts() == starts and logCount("restic ipc error") == 0)
end

print("== payload shapes")

do
  boot({ interval_minutes = 5, job_timeout_minutes = 180 })
  drain()

  -- retention preview (contract 4.7: kind, at, ok, keepCount, removeCount, remove, truncated)
  onIpc("forget-dry-run")
  check("forget-dry-run starts a dry run",
    scriptText():find("'--dry-run'", 1, true) ~= nil and scriptText():find("'--prune'", 1, true) == nil)
  exitJob('{"keep":[{"id":"aaaa1111","short_id":"aaaa1111","time":"2026-09-08T13:36:42+00:00"}],'
    .. '"remove":[{"id":"bbbb2222","short_id":"bbbb2222","time":"2026-09-08T03:36:42+00:00"}],'
    .. '"reasons":{}}\n', 0)
  local preview = H.published["restic_job"]
  check("the retention preview publishes its shape",
    preview ~= nil and preview.kind == "forget-dry" and preview.ok == true
      and preview.keepCount == 1 and preview.removeCount == 1, preview and preview.kind)
  check("the retention preview lists what would go",
    preview.remove ~= nil and preview.remove[1] ~= nil and preview.remove[1].id == "bbbb2222"
      and preview.remove[1].shortId == "bbbb2222" and preview.remove[1].time ~= nil,
    preview.remove and preview.remove[1] and preview.remove[1].id)
  check("the retention preview is not truncated", preview.truncated == false)

  -- restore preview (contract 4.7: kind, at, ok, snapshot, target, files)
  onIpc("restore-dry-run", '{"snapshot":"abcdef12"}')
  check("the restore preview runs restic restore --dry-run",
    scriptText():find("'restore'", 1, true) ~= nil
      and scriptText():find("'--dry-run'", 1, true) ~= nil
      and scriptText():find("'/tmp/restore'", 1, true) ~= nil)
  exitJob('{"message_type":"summary","total_files":5,"files_restored":5,"total_bytes":2006,'
    .. '"bytes_restored":2006}\n', 0)
  local restored = H.published["restic_job"]
  check("the restore preview publishes its shape",
    restored ~= nil and restored.kind == "restore-dry" and restored.ok == true
      and restored.snapshot == "abcdef12" and restored.target == "/tmp/restore"
      and restored.files == 5, restored and (restored.kind .. " " .. tostring(restored.files)))

  -- the real restore, same guard
  onIpc("restore", '{"snapshot":"abcdef12","target":"/tmp/restore"}')
  check("the real restore is a plain restore",
    scriptText():find("'restore'", 1, true) ~= nil
      and scriptText():find("'--dry-run'", 1, true) == nil)
  exitJob('{"message_type":"summary","total_files":5,"files_restored":5}\n', 0)
  check("a finished restore notifies", logCount("notify: Restore complete") == 1)
  check("a finished restore is persisted", readState().lastRestoreAt ~= nil)

  -- files listing (contract 4.7: snapshot, entries, truncated, at, ok)
  onIpc("ls", '{"snapshot":"abcdef12"}')
  exitJob('{"message_type":"snapshot","id":"abcdef12"}\n'
    .. '{"name":"a.bin","type":"file","path":"/tmp/data/a.bin","size":2000}\n'
    .. '{"name":"sub","type":"dir","path":"/tmp/data/sub"}\n', 0)
  local files = H.published["restic_files"]
  check("the file listing publishes its shape",
    files ~= nil and files.snapshot == "abcdef12" and files.ok == true
      and files.truncated == false and files.at ~= nil, files and files.snapshot)
  check("the file listing carries path, type and size",
    files.entries[1].path == "/tmp/data/a.bin" and files.entries[1].type == "file"
      and files.entries[1].size == 2000,
    files.entries[1] and tostring(files.entries[1].path))

  -- diff (contract 4.7: from, to, added, removed, changed, truncated, at, ok)
  onIpc("diff", '{"from":"11111111","to":"abcdef12"}')
  exitJob('{"message_type":"change","path":"/tmp/data/new.bin","modifier":"+"}\n'
    .. '{"message_type":"change","path":"/tmp/data/gone.bin","modifier":"-"}\n'
    .. '{"message_type":"statistics","changed_files":0}\n', 0)
  local diff = H.published["restic_diff"]
  check("the diff publishes its shape",
    diff ~= nil and diff.from == "11111111" and diff.to == "abcdef12" and diff.ok == true
      and diff.added == 1 and diff.removed == 1 and diff.changed == 0 and diff.truncated == false,
    diff and tostring(diff.added))

  -- repository stats (contract 4.7: totalBytes, totalFileCount, snapshotsCount, updatedAt, ok)
  onIpc("stats")
  drain()
  local stats = H.published["restic_stats"]
  check("the stats card publishes its shape",
    stats ~= nil and stats.totalBytes == 1024 and stats.totalFileCount == 7
      and stats.snapshotsCount == 2 and stats.ok == true and stats.updatedAt ~= nil,
    stats and tostring(stats.totalBytes))

  -- init and unlock
  onIpc("unlock")
  check("unlock asks restic to drop every lock",
    scriptText():find("'unlock'", 1, true) ~= nil
      and scriptText():find("'--remove-all'", 1, true) ~= nil
      and scriptText():find("'--no-lock'", 1, true) == nil)
  exitJob('{"message_type":"summary","removed":1}\n', 0)
  drain()

  onIpc("init")
  local _, initPaths = lastJob()
  check("init runs restic init", scriptText():find("'init'", 1, true) ~= nil)
  exitJob('{"message_type":"initialized","id":"abc","repository":"/tmp/repo"}\n', 0)
  check("a successful init clears initNeeded", status().initNeeded == false)
  check("a successful init notifies", logCount("notify: Restic repository initialised") == 1)

  -- job-log re-publishes the last job's log
  onIpc("job-log")
  local joblog = H.published["restic_joblog"]
  check("job-log republishes the last job's log reference",
    joblog ~= nil and joblog.kind == "init" and joblog.logPath == initPaths.log
      and logHas("initialized"), joblog and tostring(joblog.logPath))
  noLogBody("a republished init job", joblog)
  fullLogPayload("a republished init job", joblog)
end

print("== the log viewer survives a restart")

do
  boot({ interval_minutes = 5, job_timeout_minutes = 180 })
  drain()
  onIpc("backup-now")
  local _, paths = lastJob()
  exitJob('{"message_type":"summary","total_files_processed":2}\n', 0)
  local logPath = paths.log
  check("the last log path is persisted", readState().lastLog == logPath, tostring(readState().lastLog))
  local firstPath = H.published["restic_joblog"].logPath

  restart({ interval_minutes = 5, job_timeout_minutes = 180 })
  drain()
  check("the persisted log is republished after a restart",
    H.published["restic_joblog"] ~= nil and H.published["restic_joblog"].kind == "backup"
      and H.published["restic_joblog"].logPath == firstPath,
    H.published["restic_joblog"] and tostring(H.published["restic_joblog"].logPath))
  check("the restart still knows the last run", status().lastRun ~= nil and status().lastRun.ok == true)

  -- [0.4.0] The re-publish is a REFERENCE: the log file is deleted from the harness's file map, so
  -- no read of it can succeed, and the payload must still publish its metadata and its path. This is
  -- the tick-level proof that the service publishes where the log is, not its text (contract 2.3).
  H.files[logPath] = nil
  onIpc("job-log")
  check("a re-publish with no log file left still publishes the metadata and the path",
    H.published["restic_joblog"] ~= nil and H.published["restic_joblog"].kind == "backup"
      and H.published["restic_joblog"].logPath == logPath
      and logCount("restic ipc error") == 0,
    H.published["restic_joblog"] and tostring(H.published["restic_joblog"].logPath))
  noLogBody("a re-publish with the log gone", H.published["restic_joblog"])
  fullLogPayload("a re-publish with the log gone", H.published["restic_joblog"])
end

print("== scheduled integrity checks")

do
  -- Never checked, interval set: due immediately, reading the first rotating slice. The backup
  -- interval is deliberately long so this timeline measures checks only -- `update()` runs both
  -- schedules and a backup would take the single-job guard first.
  boot({ interval_minutes = 1440, check_interval_hours = 1, check_subset = "1/4" })
  drain()
  update()
  check("a due check starts on the next tick", jobStarts() == 1, jobStarts())
  check("the check reads the first rotating slice",
    scriptText():find("'--read-data-subset=1/4'", 1, true) ~= nil, scriptText())
  check("the check is not a read-only call",
    scriptText():find("'--no-lock'", 1, true) == nil)
  local persisted = readState()
  check("the rotation advances so the next check reads elsewhere",
    persisted ~= nil and persisted.checkRotationIndex == 1, persisted and tostring(persisted.checkRotationIndex))

  exitJob('{"message_type":"summary","num_errors":0}\n', 0)
  local checks = status().checks
  check("the check result is published", checks ~= nil and checks.lastAt ~= nil
    and checks.lastOk == true and checks.numErrors == 0, checks and tostring(checks.lastOk))
  persisted = readState()
  check("the check time is persisted", persisted.lastCheckAt == math.floor(H.nowMs / 1000),
    persisted and tostring(persisted.lastCheckAt))

  update()
  check("a check that just ran is not due again", jobStarts() == 1, jobStarts())
  H.nowMs = (math.floor(H.nowMs / 1000) + 3600 + 1) * 1000
  update()
  check("a check is due after its interval", jobStarts() == 2, jobStarts())
  check("the rotation moves on to the next slice",
    scriptText():find("'--read-data-subset=2/4'", 1, true) ~= nil, scriptText())
  exitJob('{"message_type":"summary","num_errors":3}\n', 0)
  check("check errors are published", status().checks.numErrors == 3,
    tostring(status().checks.numErrors))

  -- Checks off: never run, whatever the clock says.
  boot({ interval_minutes = 1440, check_interval_hours = 0 })
  drain()
  H.nowMs = (NOW_SEC + 30 * 24 * 3600) * 1000
  update()
  check("scheduled checks are off when the interval is 0", jobsRunning("check") == 0, jobsRunning("check"))

  -- A percentage subset has no slots: it must not be turned into a full read.
  boot({ interval_minutes = 1440, check_interval_hours = 1, check_subset = "5%" })
  drain()
  update()
  check("a percentage subset is passed through unchanged",
    scriptText():find("'--read-data-subset=5%'", 1, true) ~= nil, scriptText())
end

print("== scheduled backup re-arms from the last success")

do
  boot({ interval_minutes = 60, job_timeout_minutes = 180 })
  drain()
  H.nowMs = (NOW_SEC - 60) * 1000
  onIpc("backup-now")
  exitJob('{"message_type":"summary","total_files_processed":1}\n', 0)
  check("the next run is a full interval after the success",
    status().nextRun == NOW_SEC - 60 + 3600, tostring(status().nextRun))
  check("the next run is persisted", readState().nextRunAt == NOW_SEC - 60 + 3600,
    tostring(readState().nextRunAt))

  -- An interval change re-derives the schedule and stores it.
  H.config.interval_minutes = 120
  H.nowMs = (NOW_SEC + 60) * 1000
  onConfigChanged()
  drain()
  check("a changed interval re-derives the next run", status().nextRun == NOW_SEC - 60 + 7200,
    tostring(status().nextRun))
  check("the re-derived schedule is persisted", readState().nextRunAt == NOW_SEC - 60 + 7200,
    tostring(readState().nextRunAt))
end

do
  -- The plugin runs its own schedule only in plugin mode.
  boot({ mode = "observe", interval_minutes = 5 })
  drain()
  H.nowMs = (NOW_SEC + 30) * 1000
  update()
  check("observe mode never starts a backup", jobStarts() == 0, jobStarts())
  onIpc("backup-now")
  check("observe mode refuses a manual backup too", jobStarts() == 0, jobStarts())
  check("the refusal is explained", logCount("error: ") == 1)
end

do
  -- A missing repository is reported, not acted on.
  boot({ repository = "" })
  drain()
  onIpc("backup-now")
  check("no repository means no job", jobStarts() == 0, jobStarts())
  onIpc("stats")
  drain()
  check("stats without a repository publishes nothing", H.published["restic_stats"] == nil)
end

print("== a finished job publishes a reference to its log, not the log")

do
  -- The real 473-byte one-line log from this machine: it used to BE the Log tab, formatted here and
  -- copied into the published payload from this callback. It is now the panel's file to read.
  local summary = readFixture("backup-summary.jsonl")
  boot({ interval_minutes = 1440, check_interval_hours = 0 })
  drain()
  onIpc("backup-now")
  local _, paths = lastJob()
  check("the backup job started", paths ~= nil)
  exitJob(summary, 0)

  local joblog = H.published["restic_joblog"]
  check("the finished job publishes the log's path",
    type(joblog) == "table" and joblog.logPath == paths.log, joblog and tostring(joblog.logPath))
  noLogBody("a finished job", joblog)
  fullLogPayload("a finished job", joblog)
  check("the published path is the log the runner wrote",
    noctalia.readFile(joblog.logPath) == summary)
  check("the run's own metadata is untouched",
    joblog.kind == "backup" and joblog.ok == true and joblog.exitCode == 0
      and joblog.cancelled == false and joblog.at ~= nil,
    tostring(joblog.kind) .. "/" .. tostring(joblog.ok))

  -- The refresh button / the job-log event: the re-publish path carries the same reference.
  local before = H.published["restic_joblog"]
  onIpc("job-log")
  local refreshed = H.published["restic_joblog"]
  check("a republish carries the same log reference",
    refreshed ~= before and type(refreshed) == "table" and refreshed.kind == "backup"
      and refreshed.logPath == paths.log,
    refreshed and tostring(refreshed.logPath))
  noLogBody("a republished job", refreshed)
  fullLogPayload("a republished job", refreshed)

  -- initialise() republishes from the persisted path, so the Log tab survives a shell restart.
  restart({ interval_minutes = 1440, check_interval_hours = 0 })
  drain()
  local revived = H.published["restic_joblog"]
  check("a restart republishes the log reference",
    type(revived) == "table" and revived.kind == "backup" and revived.logPath == paths.log,
    revived and tostring(revived.logPath))
  noLogBody("a restarted service", revived)
  fullLogPayload("a restarted service", revived)
end

print("== a running job publishes a reference and reads no log at all")

do
  boot({ interval_minutes = 1440, check_interval_hours = 0 })
  drain()
  onIpc("backup-now")
  local _, paths = lastJob()
  check("the running job has a log path", paths ~= nil)

  -- The runner appends as restic writes, so the panel has to be told the log grew, poll by poll.
  H.files[paths.log] = "== post-backup command ==\n"
  update()
  local first = H.published["restic_joblog"]
  check("the first bytes of a running job publish a live reference",
    type(first) == "table" and first.logPath == paths.log, first and tostring(first.logPath))
  check("a run in flight is published as unfinished, not as a failure",
    first.kind == "backup" and first.ok == false and first.exitCode == nil,
    tostring(first.ok) .. "/" .. tostring(first.exitCode))
  noLogBody("a running job", first)

  -- The live refresh is throttled: every republish re-renders the panel inside this service
  -- callback, and on a 97 KB listing job that tripped the host's per-callback CPU budget, so a
  -- growth poll inside the window must publish nothing at all.
  H.files[paths.log] = "== post-backup command ==\npruned 3 old dumps\n"
  update()
  check("a growth poll inside the live-refresh window publishes nothing",
    H.published["restic_joblog"] == first)

  H.nowMs = (NOW_SEC + 6) * 1000
  H.files[paths.log] = "== post-backup command ==\npruned 3 old dumps\nstill going\n"
  update()
  local second = H.published["restic_joblog"]
  check("past the window the payload follows the growing log",
    second ~= first and type(second) == "table" and second.logPath == paths.log
      and second.exitCode == nil,
    second and tostring(second.logPath))
  noLogBody("a refreshed running job", second)

  -- A tick that sees no new bytes must not publish: the panel re-renders on every state change.
  update()
  check("an idle tick publishes nothing", H.published["restic_joblog"] == second)
  update()
  check("a second idle tick publishes nothing either", H.published["restic_joblog"] == second)

  -- A payload's own weight: the longest string it holds anywhere. The fix's whole point is that this
  -- does not grow with the log -- a 97 KB job used to publish ~200 lines plus the formatter's copy
  -- (~104 KiB per tick, measured), which is what the host's per-callback CPU budget killed.
  local function longestString(value, seen)
    local longest = 0
    seen = seen or {}
    for _, item in pairs(value) do
      if type(item) == "string" then
        longest = math.max(longest, #item)
      elseif type(item) == "table" and not seen[item] then
        seen[item] = true
        longest = math.max(longest, longestString(item, seen))
      end
    end
    return longest
  end

  -- [0.4.0] The size that killed this tick live: a ~97 KB `ls --json` job log. The payload published
  -- from the growth tick must not carry a byte of it.
  H.nowMs = (NOW_SEC + 12) * 1000
  H.files[paths.log] = string.rep(readFixture("ls-list.jsonl"), 7)
  update()
  local big = H.published["restic_joblog"]
  check("a 97 KB job log publishes a payload that carries no part of it",
    #H.files[paths.log] > 97000 and type(big) == "table" and big.logPath == paths.log
      and longestString(big) <= #paths.log,
    tostring(#H.files[paths.log]) .. " log bytes, longest published string "
      .. tostring(type(big) == "table" and longestString(big) or "n/a"))
  noLogBody("a 97 KB job log", big)

  -- [0.4.0] THE FIX, proved the only way it can be: the log is deleted from the harness's file map,
  -- so the service cannot read a single byte of it, and the tick must not need to -- it publishes
  -- WHERE the log is and the panel reads the file itself. The job still finishes, and its payload
  -- still carries the run's metadata and its path.
  H.files[paths.log] = nil
  update()
  check("a tick with the log gone reads nothing and publishes nothing",
    H.published["restic_joblog"] == big)
  H.files[paths.exit] = "0\n"
  update()
  local finished = H.published["restic_joblog"]
  check("a job whose log is gone still publishes its metadata and its path",
    finished ~= big and type(finished) == "table" and finished.ok == true
      and finished.exitCode == 0 and finished.logPath == paths.log,
    finished and tostring(finished.logPath))
  noLogBody("a finished job with its log gone", finished)
  fullLogPayload("a finished job with its log gone", finished)
  check("no read of the missing log raised anything",
    logCount("restic ipc error") == 0, logCount("restic ipc error"))

  -- And with no job in flight, no tick touches the log ever again.
  update()
  update()
  check("no job active means no log publish", H.published["restic_joblog"] == finished)
end

print("== the retention preview is invalidated by the prune that acts on it")

do
  -- Started jobs whose script runs a forget dry run (the subcommand plus --dry-run).
  local function dryRunJobs()
    local count = 0
    for _, cmd in ipairs(H.commands) do
      if cmd[1] == "/bin/sh" then
        local script = H.files[cmd[2]] or ""
        if script:find("'forget'", 1, true) ~= nil
            and script:find("'--dry-run'", 1, true) ~= nil then
          count = count + 1
        end
      end
    end
    return count
  end

  boot({ interval_minutes = 5 })
  drain()

  -- A preview on screen: one snapshot to keep, one to remove.
  onIpc("forget-dry-run")
  exitJob('{"keep":[{"id":"aaaa1111","short_id":"aaaa1111","time":"2026-09-08T13:36:42+00:00"}],'
    .. '"remove":[{"id":"bbbb2222","short_id":"bbbb2222","time":"2026-09-08T03:36:42+00:00"}],'
    .. '"reasons":{}}\n', 0)
  local preview = H.published["restic_job"]
  check("a preview with something to remove is on screen before the prune",
    preview ~= nil and preview.kind == "forget-dry" and preview.removeCount == 1,
    preview and tostring(preview.removeCount))

  local dryRuns = dryRunJobs()

  -- Confirm the prune: it runs for real, and finishes successfully.
  onIpc("forget")
  check("the confirmed prune runs restic forget with --prune",
    scriptText():find("'--prune'", 1, true) ~= nil, scriptText():sub(1, 120))
  exitJob('{"message_type":"summary","total_files":0}\n', 0)

  -- [0.6.2] The list on screen described the repository BEFORE this prune. Left standing it offers a
  -- second prune of snapshots that are already gone, against counts nothing has recomputed.
  check("applying the policy re-runs the dry run, so the preview cannot outlive the prune it acted on",
    dryRunJobs() == dryRuns + 1, tostring(dryRuns) .. " -> " .. tostring(dryRunJobs()))

  -- And the refreshed preview reports the policy against the repository as it now is.
  exitJob('{"keep":[{"id":"aaaa1111","short_id":"aaaa1111","time":"2026-09-08T13:36:42+00:00"}],'
    .. '"remove":null,"reasons":{}}\n', 0)
  local after = H.published["restic_job"]
  check("the refreshed preview reports what is left, not what was removed",
    after ~= nil and after.kind == "forget-dry" and after.removeCount == 0 and after.keepCount == 1,
    after and (tostring(after.keepCount) .. " keep / " .. tostring(after.removeCount) .. " remove"))
end

print(string.format("\n%s -- %d failure(s)", failures == 0 and "ALL PASS" or "FAILURES", failures))
os.exit(failures == 0 and 0 or 1)
