--!nonstrict
-- Restore verification tests: plugin/restic-snapshots/service.luau driven for real.
-- Run from the repo root:  lua5.4 tests/lua/verify_test.lua
--
-- This is the feature that turns "a backup ran" into "the backup restores", and it runs against
-- the user's real repository, so what these tests pin down is the *honesty* of the result:
--   * an all-matching verification publishes lastOk = true with the real counts;
--   * a live file that genuinely differs is a failure, notified exactly once;
--   * a live file that legitimately changed after the snapshot, or went away, is skipped and not
--     blamed on the backup;
--   * anything that stops the comparison from meaning something -- no usable files, a failed file
--     listing, a failed restore, a restored copy that cannot be read back -- publishes
--     lastOk = false with a reason instead of reporting success;
--   * the cadence gate, the IPC refusals (hostile targets), and the store round-trip.
--
-- The harness plumbing mirrors tests/lua/service_test.lua: H.pending holds runAsync callbacks,
-- H.files is the filesystem the store and the scratch directory live in, H.nowMs is settable for
-- time travel, and H.decodeFn installs a real JSON decoder (the store's own output is read back).

package.path = "tests/lua/?.lua;" .. package.path
local H = dofile("tests/lua/harness.lua")

local failures = 0
local function check(name, condition, detail)
  if condition then
    print("ok   " .. name)
  else
    failures = failures + 1
    print("FAIL " .. name .. (detail ~= nil and ("  -- " .. tostring(detail)) or ""))
  end
end

local NOW_MS = 1788874602000
local NOW_SEC = 1788874602
local JOB_DIR = "/tmp/restic-data/jobs"
local STATE_PATH = "/tmp/restic-data/state.json"
local RESTORE_TARGET = "/tmp/restore"

-- The newest snapshot the tests verify against: NOW - 60s, in the offset form restic emits.
local SNAP_ID = "c9ff02c0c9ff02c0c9ff02c0c9ff02c0"
local SNAP_TIME = "2026-09-08T13:35:42+00:00"
local SNAP_AT = 1788874542

-- ── a real JSON decoder ──────────────────────────────────────────────────────
-- The store writes state.json and the service reads it back, so "does the verification survive a
-- restart" cannot be tested against a canned table map: the text is generated by the encoder.

local decodeJson
do
  local function skipSpace(text, pos)
    while true do
      local c = text:sub(pos, pos)
      if c == " " or c == "\t" or c == "\n" or c == "\r" then
        pos = pos + 1
      else
        return pos
      end
    end
  end

  local function parseValue(text, pos)
    pos = skipSpace(text, pos)
    local c = text:sub(pos, pos)
    if c == "{" then
      local out = {}
      pos = skipSpace(text, pos + 1)
      if text:sub(pos, pos) == "}" then
        return out, pos + 1
      end
      while true do
        local key, value
        key, pos = parseValue(text, pos)
        pos = skipSpace(text, pos)
        if text:sub(pos, pos) ~= ":" then
          error("expected : at " .. pos)
        end
        value, pos = parseValue(text, pos + 1)
        if value ~= nil then
          out[key] = value
        end
        pos = skipSpace(text, pos)
        local sep = text:sub(pos, pos)
        if sep == "," then
          pos = pos + 1
        elseif sep == "}" then
          return out, pos + 1
        else
          error("expected , or } at " .. pos)
        end
      end
    elseif c == "[" then
      local out = {}
      pos = skipSpace(text, pos + 1)
      if text:sub(pos, pos) == "]" then
        return out, pos + 1
      end
      while true do
        local value
        value, pos = parseValue(text, pos)
        table.insert(out, value)
        pos = skipSpace(text, pos)
        local sep = text:sub(pos, pos)
        if sep == "," then
          pos = pos + 1
        elseif sep == "]" then
          return out, pos + 1
        else
          error("expected , or ] at " .. pos)
        end
      end
    elseif c == '"' then
      local out = {}
      pos = pos + 1
      while true do
        local ch = text:sub(pos, pos)
        if ch == "" then
          error("unterminated string")
        elseif ch == '"' then
          return table.concat(out), pos + 1
        elseif ch == "\\" then
          local esc = text:sub(pos + 1, pos + 1)
          if esc == "n" then
            table.insert(out, "\n")
          elseif esc == "t" then
            table.insert(out, "\t")
          elseif esc == "r" then
            table.insert(out, "\r")
          elseif esc == "b" then
            table.insert(out, "\b")
          elseif esc == "f" then
            table.insert(out, "\f")
          elseif esc == "u" then
            table.insert(out, utf8.char(tonumber(text:sub(pos + 2, pos + 5), 16) or 63))
            pos = pos + 4
          else
            table.insert(out, esc)
          end
          pos = pos + 2
        else
          table.insert(out, ch)
          pos = pos + 1
        end
      end
    elseif text:sub(pos, pos + 3) == "true" then
      return true, pos + 4
    elseif text:sub(pos, pos + 4) == "false" then
      return false, pos + 5
    elseif text:sub(pos, pos + 3) == "null" then
      return nil, pos + 4
    end
    local stop = pos
    while stop <= #text and text:sub(stop, stop):match("[%d%.eE%+%-]") do
      stop = stop + 1
    end
    local number = tonumber(text:sub(pos, stop - 1))
    if number == nil then
      error("bad value at " .. pos)
    end
    return number, stop
  end

  decodeJson = function(text)
    if type(text) ~= "string" then
      return nil
    end
    local ok, value = pcall(parseValue, text, 1)
    if not ok then
      return nil
    end
    return value
  end
end

local function readState()
  local text = H.files[STATE_PATH]
  if type(text) ~= "string" then
    return nil
  end
  return decodeJson(text)
end

-- ── harness plumbing ─────────────────────────────────────────────────────────

local DEFAULTS = {}
for key, value in pairs(H.config) do
  if type(value) == "table" then
    local copy = {}
    for k, v in pairs(value) do
      copy[k] = v
    end
    DEFAULTS[key] = copy
  else
    DEFAULTS[key] = value
  end
end

local runner = { pairs = {} }
local snapshotJson = "[]"
local snapshotExit = 0
local lsText = ""
local lsExit = 0
local lsStderr = ""

local function argvHas(cmd, needle)
  for _, value in ipairs(cmd) do
    if value == needle then
      return true
    end
  end
  return false
end

-- Answer every read-only runAsync the service issued, classifying it by argv. The verification
-- issues two in a row (snapshots, then ls) and then starts its job, so the drain loops until
-- nothing is left pending, exactly like a settled shell.
local function drain()
  local answered = 0
  while #runner.pairs > 0 do
    local batch = runner.pairs
    runner.pairs = {}
    for _, entry in ipairs(batch) do
      local cb = entry.cb
      if cb ~= nil then
        answered = answered + 1
        local cmd = entry.cmd
        local result = { exitCode = 0, stdout = "", stderr = "" }
        if cmd[1] == "sh" then
          result.stdout = "/usr/bin:/bin\n"
        elseif argvHas(cmd, "version") then
          result.stdout = "restic 0.19.1 compiled with go1.26.4 on linux/amd64\n"
        elseif argvHas(cmd, "snapshots") then
          result.exitCode = snapshotExit
          result.stdout = snapshotJson
        elseif argvHas(cmd, "ls") then
          result.exitCode = lsExit
          result.stdout = lsText
          result.stderr = lsStderr
        elseif argvHas(cmd, "stats") then
          result.stdout = '{"total_size":1024,"total_file_count":7,"snapshots_count":2}\n'
        end
        cb(result)
      end
    end
  end
  return answered
end

local function installRunner()
  runner.pairs = {}
  _G.noctalia.runAsync = function(cmd, cb)
    table.insert(H.commands, cmd)
    table.insert(runner.pairs, { cmd = cmd, cb = cb })
    return true
  end
end

-- The harness answers listDir with nothing, which would make the verification's cleanup walk
-- untestable. List the immediate children of `dir` out of H.files instead. The job directory is
-- deliberately excluded: these tests read a finished job's script and log back, and the hourly
-- sweep ageing those out is jobs_test's subject, not this file's.
local function installListDir()
  _G.noctalia.listDir = function(dir)
    if dir == JOB_DIR then
      return {}
    end
    local prefix = dir .. "/"
    local seen = {}
    local names = {}
    for path in pairs(H.files) do
      if path:sub(1, #prefix) == prefix then
        local first = path:sub(#prefix + 1):match("^([^/]+)")
        if first ~= nil and first ~= "" and not seen[first] then
          seen[first] = true
          table.insert(names, first)
        end
      end
    end
    return names
  end
end

local function snapshotsJson(entries)
  local parts = {}
  for _, entry in ipairs(entries) do
    table.insert(parts, string.format(
      '{"id":"%s","short_id":"%s","time":"%s","hostname":"cachyos","tags":["noctalia"],'
        .. '"paths":["/tmp/data"],"summary":{"total_files_processed":3,'
        .. '"total_bytes_processed":100,"data_added":10}}',
      entry.id, entry.id:sub(1, 8), entry.time))
  end
  return "[" .. table.concat(parts, ",") .. "]"
end

-- `restic ls --json`: one snapshot record, then one node record per entry. `size` is omitted for
-- anything that is not a regular file, exactly as restic emits it.
local function lsJson(entries)
  local lines = { '{"message_type":"snapshot","id":"' .. SNAP_ID .. '"}' }
  for _, entry in ipairs(entries) do
    local parts = {
      '"name":"' .. entry[1] .. '"',
      '"type":"' .. entry[2] .. '"',
      '"path":"' .. entry[3] .. '"',
    }
    if entry[4] ~= nil then
      table.insert(parts, '"size":' .. tostring(entry[4]))
    end
    table.insert(lines, "{" .. table.concat(parts, ",") .. "}")
  end
  return table.concat(lines, "\n") .. "\n"
end

-- Boot the real service on a fresh harness, with optional config/file overrides.
local function boot(config, files, nowMs)
  H.install("plugin/restic-snapshots")
  for key, value in pairs(DEFAULTS) do
    if type(value) == "table" then
      local copy = {}
      for k, v in pairs(value) do
        copy[k] = v
      end
      H.config[key] = copy
    else
      H.config[key] = value
    end
  end
  H.config.restore_target = RESTORE_TARGET
  -- The 0.3.0 settings are not in the harness's own config table, so they are cleared explicitly:
  -- without this a block that set an interval would leak it into every later block.
  H.config.verify_interval_hours = nil
  H.config.verify_file_count = nil
  snapshotJson = snapshotsJson({ { id = SNAP_ID, time = SNAP_TIME } })
  snapshotExit = 0
  -- The `ls` fixture is deliberately NOT reset here: each block sets the listing it wants to be
  -- verified *before* booting, and a reset would wipe it. The exit code and stderr are reset, so a
  -- block that simulates a failing listing cannot leak that failure into the next one.
  lsExit = 0
  lsStderr = ""
  H.decodeFn = decodeJson
  H.nowMs = nowMs or NOW_MS
  for key, value in pairs(files or {}) do
    H.files[key] = value
  end
  for key, value in pairs(config or {}) do
    H.config[key] = value
  end
  installRunner()
  installListDir()
  H.load("service.luau")
  return H
end

-- Restart the service keeping the filesystem it left behind (a shell restart, in one call).
local function restart(config, nowMs)
  local carried = H.files
  H.install("plugin/restic-snapshots")
  H.files = carried
  H.decodeFn = decodeJson
  for key, value in pairs(DEFAULTS) do
    if type(value) == "table" then
      local copy = {}
      for k, v in pairs(value) do
        copy[k] = v
      end
      H.config[key] = copy
    else
      H.config[key] = value
    end
  end
  H.config.restore_target = RESTORE_TARGET
  H.config.verify_interval_hours = nil
  H.config.verify_file_count = nil
  for key, value in pairs(config or {}) do
    H.config[key] = value
  end
  H.nowMs = nowMs or NOW_MS
  installRunner()
  installListDir()
  H.load("service.luau")
end

-- ── introspection ────────────────────────────────────────────────────────────

local function status()
  return H.published["restic_status"]
end

local function verifyState()
  local published = status()
  return published ~= nil and published.verify or nil
end

local function jobStarts()
  local count = 0
  for _, cmd in ipairs(H.commands) do
    if cmd[1] == "/bin/sh" then
      count = count + 1
    end
  end
  return count
end

-- Started jobs whose generated script runs a given restic subcommand.
local function jobsRunning(subcommand)
  local count = 0
  for _, cmd in ipairs(H.commands) do
    if cmd[1] == "/bin/sh" then
      local script = H.files[cmd[2]] or ""
      if script:find("'" .. subcommand .. "'", 1, true) ~= nil then
        count = count + 1
      end
    end
  end
  return count
end

-- The job the service started last, by its generated script, plus the paths the runner wrote to.
local function lastJob()
  for i = #H.commands, 1, -1 do
    local cmd = H.commands[i]
    if cmd[1] == "/bin/sh" and type(cmd[2]) == "string" then
      local token = cmd[2]:match("([^/]+)%.sh$")
      if token ~= nil then
        return token, {
          log = JOB_DIR .. "/" .. token .. ".jsonl",
          status = JOB_DIR .. "/" .. token .. ".status",
          exit = JOB_DIR .. "/" .. token .. ".exit",
          pid = JOB_DIR .. "/" .. token .. ".pid",
          script = cmd[2],
        }
      end
    end
  end
  return nil, nil
end

local function scriptText()
  local _, paths = lastJob()
  return paths ~= nil and (H.files[paths.script] or "") or ""
end

-- `restic restore <id> --target <dir>` -- the scratch directory the verification chose. Read out
-- of the generated script, so the test asserts what the service really told restic.
local function restoreTargetFromScript()
  return scriptText():match("'%-%-target' '([^']*)'")
end

-- The per-file `--include` arguments, in the order the service passed them.
local function includesFromScript()
  local out = {}
  for path in scriptText():gmatch("'%-%-include' '([^']*)'") do
    table.insert(out, path)
  end
  return out
end

local function logCount(needle)
  local count = 0
  for _, line in ipairs(H.logs) do
    if line:find(needle, 1, true) ~= nil then
      count = count + 1
    end
  end
  return count
end

-- Finish the job in flight the way the runner does: the whole log, then the exit file.
local function exitJob(logText2, exitCode)
  local _, paths = lastJob()
  H.files[paths.log] = logText2
  H.files[paths.exit] = tostring(exitCode) .. "\n"
  update()
  drain()
end

-- What restic restores: give the job's chosen files a restored copy under the scratch directory.
local function restoreWrites(resolve)
  local scratch = restoreTargetFromScript()
  for _, path in ipairs(includesFromScript()) do
    H.files[scratch .. path] = resolve(path)
  end
  return scratch
end

-- ── the cadence gate (pure) ──────────────────────────────────────────────────

print("== the cadence gate mirrors the check schedule")

do
  H.install("plugin/restic-snapshots")
  local schedule = H.load("lib/schedule.luau")

  check("an interval of 0 means off", schedule.verifyDue(NOW_SEC, nil, 0) == false)
  check("no interval at all means off", schedule.verifyDue(NOW_SEC, NOW_SEC - 86400, nil) == false)
  check("a verification that never ran is due", schedule.verifyDue(NOW_SEC, nil, 2) == true)
  check("inside the interval it is not due", schedule.verifyDue(NOW_SEC, NOW_SEC - 3600, 2) == false)
  check("at the interval it is due", schedule.verifyDue(NOW_SEC + 7200, NOW_SEC, 2) == true)
  check("past the interval it is due", schedule.verifyDue(NOW_SEC + 7201, NOW_SEC, 2) == true)

  -- The cadence rule must not drift from the integrity check's: same inputs, same answer.
  local mismatches = 0
  for _, interval in ipairs({ 0, 1, 6, 24 }) do
    for _, offset in ipairs({ 0, 1, 3599, 3600, 7199, 86400 }) do
      local last = NOW_SEC - offset
      if schedule.verifyDue(NOW_SEC, last, interval)
          ~= schedule.checkDue(NOW_SEC, last, interval) then
        mismatches = mismatches + 1
      end
    end
  end
  check("verifyDue agrees with checkDue on every interval/offset pair", mismatches == 0, mismatches)
end

print("== a verification that matches proves the backup restores")

do
  lsText = lsJson({
    { "a.conf", "file", "/tmp/data/a.conf", 6 },
    { "b.conf", "file", "/tmp/data/b.conf", 6 },
    { "c.conf", "file", "/tmp/data/c.conf", 8 },
    { "sub", "dir", "/tmp/data/sub", nil },
    { "link", "symlink", "/tmp/data/link", nil },
  })
  boot({ interval_minutes = 1440, verify_interval_hours = 0, verify_file_count = 3 }, {
    ["/tmp/data/a.conf"] = "alpha\n",
    ["/tmp/data/b.conf"] = "bravo\n",
    ["/tmp/data/c.conf"] = "charlie\n",
  })

  check("no verification runs while it is configured off", (function()
    update()
    return jobStarts() == 0
  end)(), jobStarts())

  onIpc("verify-restore", "{}")
  drain()
  check("an on-demand verification starts a restore job", jobsRunning("restore") == 1,
    jobsRunning("restore"))
  check("the restore is a real one, not a dry run",
    scriptText():find("'--dry-run'", 1, true) == nil)
  local scratch = restoreTargetFromScript()
  check("the restore writes into a scratch directory under the restore target",
    scratch == RESTORE_TARGET .. "/.verify/" .. NOW_SEC, tostring(scratch))
  check("nothing is written to the live files by the job",
    scriptText():find("'backup'", 1, true) == nil and scriptText():find("'forget'", 1, true) == nil)

  local includes = includesFromScript()
  check("exactly the configured number of files is restored", #includes == 3, #includes)
  check("only regular files are chosen, evenly spaced through the listing",
    includes[1] == "/tmp/data/a.conf" and includes[2] == "/tmp/data/b.conf"
      and includes[3] == "/tmp/data/c.conf", table.concat(includes, ","))
  check("the previous result is not published before the job finishes",
    verifyState() == nil or verifyState().lastAt ~= NOW_SEC, tostring(verifyState()))

  restoreWrites(function(path)
    return H.files[path]
  end)
  local notificationsBefore = logCount("error: Restore verification failed")
  exitJob('{"message_type":"summary","files_restored":3}\n', 0)

  local published = verifyState()
  check("the verification result is published", published ~= nil, tostring(published))
  check("an all-matching verification is ok", published.lastOk == true, tostring(published.lastOk))
  check("every chosen file was checked", published.checked == 3, tostring(published.checked))
  check("every chosen file matched", published.matched == 3, tostring(published.matched))
  check("nothing failed", published.failed == 0, tostring(published.failed))
  check("the detail reads as a human sentence", published.detail == "3 of 3 files matched",
    published.detail)
  check("the verification is timestamped", published.lastAt == NOW_SEC, tostring(published.lastAt))
  check("a successful verification does not notify",
    logCount("error: Restore verification failed") == notificationsBefore)
  check("the result is persisted", readState().lastVerifyAt == NOW_SEC
    and readState().lastVerifyOk == true and readState().lastVerifyChecked == 3,
    tostring(readState().lastVerifyOk))
  check("the restored copies are cleaned up", (function()
    for _, path in ipairs(includes) do
      if H.files[scratch .. path] ~= nil then
        return false
      end
    end
    return true
  end)())
  check("the live files are untouched", H.files["/tmp/data/a.conf"] == "alpha\n"
    and H.files["/tmp/data/b.conf"] == "bravo\n", tostring(H.files["/tmp/data/a.conf"]))
  check("nothing was written outside the scratch directory", (function()
    local prefix = RESTORE_TARGET .. "/"
    for path in pairs(H.files) do
      if path:sub(1, #prefix) == prefix and path:sub(1, #scratch) ~= scratch then
        return false
      end
    end
    return true
  end)())
end

print("== a genuine difference is a failure, and it notifies exactly once")

do
  lsText = lsJson({ { "one.conf", "file", "/tmp/data/one.conf", 14 } })
  boot({ interval_minutes = 1440, verify_interval_hours = 0, verify_file_count = 1 }, {
    ["/tmp/data/one.conf"] = "LIVE-TEXT\n",
  })
  -- Written before the snapshot: nothing legitimate explains the difference.
  H.mtimes["/tmp/data/one.conf"] = SNAP_AT - 3600

  onIpc("verify-restore")
  drain()
  local scratch = restoreWrites(function()
    return "SNAPSHOT-TEXT\n"
  end)
  exitJob('{"message_type":"summary","files_restored":1}\n', 0)

  local published = verifyState()
  check("a differing live file is a failure", published.lastOk == false, tostring(published.lastOk))
  check("the difference is counted", published.failed == 1 and published.matched == 0,
    tostring(published.failed) .. "/" .. tostring(published.matched))
  check("the file still counts as checked", published.checked == 1, tostring(published.checked))
  check("the detail names the file and the reason",
    published.detail:find("/tmp/data/one.conf", 1, true) ~= nil
      and published.detail:find("do not match the backup", 1, true) ~= nil, published.detail)
  check("a failing verification notifies once",
    logCount("error: Restore verification failed") == 1,
    logCount("error: Restore verification failed"))
  check("the failure is persisted", readState().lastVerifyOk == false
    and readState().lastVerifyChecked == 1)
  check("a real difference is not reported as a status error",
    status().error == "", tostring(status().error))

  -- The same failure, again: it is not news a second time. The clock moves so the second run is a
  -- distinct job (jobs.newToken is seeded from the clock).
  H.nowMs = H.nowMs + 1000
  onIpc("verify-restore")
  drain()
  restoreWrites(function()
    return "SNAPSHOT-TEXT\n"
  end)
  exitJob('{"message_type":"summary","files_restored":1}\n', 0)
  check("a repeated failure does not notify again",
    logCount("error: Restore verification failed") == 1,
    logCount("error: Restore verification failed"))

  -- And a recovery is a clean success again.
  H.files["/tmp/data/one.conf"] = "SNAPSHOT-TEXT\n"
  H.nowMs = H.nowMs + 1000
  onIpc("verify-restore")
  drain()
  restoreWrites(function()
    return "SNAPSHOT-TEXT\n"
  end)
  exitJob('{"message_type":"summary","files_restored":1}\n', 0)
  check("a recovery publishes lastOk = true", verifyState().lastOk == true,
    tostring(verifyState().lastOk))
  check("a recovery does not notify", logCount("error: Restore verification failed") == 1)
end

print("== a legitimately changed or missing live file is skipped, not failed")

do
  lsText = lsJson({ { "one.conf", "file", "/tmp/data/one.conf", 14 } })
  boot({ interval_minutes = 1440, verify_file_count = 1 }, { ["/tmp/data/one.conf"] = "CHANGED\n" })
  -- Modified after the snapshot was taken: the backup is not wrong, the file is newer.
  H.mtimes["/tmp/data/one.conf"] = SNAP_AT + 60

  onIpc("verify-restore")
  drain()
  restoreWrites(function()
    return "OLD-TEXT\n"
  end)
  exitJob('{"message_type":"summary","files_restored":1}\n', 0)

  local published = verifyState()
  check("a file modified after the snapshot is skipped rather than failed",
    published.lastOk == true and published.failed == 0, tostring(published.failed))
  check("a skipped file still counts as checked", published.checked == 1, tostring(published.checked))
  check("a skipped file is not counted as matched", published.matched == 0,
    tostring(published.matched))
  check("the detail says nothing could be compared",
    published.detail:find("none could be compared", 1, true) ~= nil, published.detail)
  check("a skip does not notify", logCount("error: Restore verification failed") == 0)
end

do
  lsText = lsJson({ { "gone.conf", "file", "/tmp/data/gone.conf", 14 } })
  boot({ interval_minutes = 1440, verify_file_count = 1 })

  onIpc("verify-restore")
  drain()
  restoreWrites(function()
    return "OLD-TEXT\n"
  end)
  exitJob('{"message_type":"summary","files_restored":1}\n', 0)

  local published = verifyState()
  check("a live file that is gone is skipped rather than failed",
    published.lastOk == true and published.failed == 0, tostring(published.failed))
  check("it still counts as checked", published.checked == 1, tostring(published.checked))
end

print("== a verification that cannot prove anything is not a success")

do
  -- Nothing restorable: a directory and a file far past the comparison bound.
  lsText = lsJson({
    { "big.bin", "file", "/tmp/data/big.bin", 8 * 1024 * 1024 },
    { "sub", "dir", "/tmp/data/sub", nil },
  })
  boot({ interval_minutes = 1440, verify_file_count = 3 })

  onIpc("verify-restore")
  drain()
  check("no usable files means no restore job at all", jobStarts() == 0, jobStarts())

  local published = verifyState()
  check("lastOk is false", published.lastOk == false, tostring(published.lastOk))
  check("nothing is claimed to have been checked",
    published.checked == 0 and published.matched == 0 and published.failed == 0,
    tostring(published.checked))
  check("the detail explains why", published.detail:find("no regular file", 1, true) ~= nil,
    published.detail)
  check("it is logged once", logCount("restic: verification could not run") == 1,
    logCount("restic: verification could not run"))
  check("it notifies once", logCount("error: Restore verification failed") == 1,
    logCount("error: Restore verification failed"))
  check("the empty result is persisted", readState().lastVerifyOk == false
    and readState().lastVerifyChecked == 0)
end

do
  -- The listing itself failed: reported, with restic's own reason, and never as a success.
  lsText = ""
  boot({ interval_minutes = 1440, verify_file_count = 1 })
  lsExit = 10
  lsStderr = "Fatal: unable to open repository at /tmp/repo\n"

  onIpc("verify-restore")
  drain()
  local published = verifyState()
  check("a failed file listing is a failure", published.lastOk == false, tostring(published.lastOk))
  check("a failed listing starts no job", jobStarts() == 0, jobStarts())
  check("the detail carries restic's reason",
    published.detail:find("unable to open repository", 1, true) ~= nil, published.detail)
  check("it notifies once", logCount("error: Restore verification failed") == 1)
end

do
  -- An empty repository: there is nothing to verify, which is a failure to prove, not a success.
  lsText = lsJson({ { "one.conf", "file", "/tmp/data/one.conf", 4 } })
  boot({ interval_minutes = 1440, verify_file_count = 1 })
  snapshotJson = "[]"

  onIpc("verify-restore")
  drain()
  local published = verifyState()
  check("an empty repository cannot verify", published.lastOk == false
    and published.detail:find("no snapshot to verify", 1, true) ~= nil, published.detail)
  check("an empty repository starts no job", jobStarts() == 0, jobStarts())
end

do
  -- The restore job failed, and the restored copy could not be read back.
  lsText = lsJson({ { "one.conf", "file", "/tmp/data/one.conf", 14 } })
  boot({ interval_minutes = 1440, verify_file_count = 1 }, { ["/tmp/data/one.conf"] = "live\n" })

  onIpc("verify-restore")
  drain()
  exitJob('{"message_type":"exit_error","code":12,"message":"Fatal: unable to open repository"}\n', 12)
  local published = verifyState()
  check("a failed restore is a failed verification", published.lastOk == false,
    tostring(published.lastOk))
  check("the detail says the restore failed",
    published.detail:find("the restore failed", 1, true) == 1, published.detail)
  check("a failed restore notifies once, not twice",
    logCount("error: Restore verification failed") == 1
      and logCount("error: Restic verify failed") == 0,
    logCount("error: Restore verification failed") .. "/" .. logCount("error: Restic verify failed"))
  check("a failed restore is still a visible status error", status().error ~= "",
    tostring(status().error))
  check("a failed restore checked nothing", published.checked == 0, tostring(published.checked))
end

do
  -- restic "succeeded" but wrote nothing we can read back: that is the self-deception case.
  lsText = lsJson({ { "one.conf", "file", "/tmp/data/one.conf", 14 } })
  boot({ interval_minutes = 1440, verify_file_count = 1 }, { ["/tmp/data/one.conf"] = "live\n" })

  onIpc("verify-restore")
  drain()
  exitJob('{"message_type":"summary","files_restored":1}\n', 0)
  local published = verifyState()
  check("a restored copy that cannot be read back is a failure",
    published.lastOk == false and published.failed == 1,
    tostring(published.lastOk) .. "/" .. tostring(published.failed))
  check("the detail names the missing copy",
    published.detail:find("no readable copy", 1, true) ~= nil, published.detail)
end

print("== the cadence runs a verification when it is due, and only then")

do
  lsText = lsJson({ { "one.conf", "file", "/tmp/data/one.conf", 5 } })
  boot({ interval_minutes = 1440, verify_interval_hours = 2, verify_file_count = 1,
    check_interval_hours = 0 }, { ["/tmp/data/one.conf"] = "same\n" })

  update()
  check("a verification that never ran is due on the first tick",
    logCount("restic: scheduled verification did not start") == 0, logCount("restic: scheduled verification did not start"))
  drain()
  check("the due verification starts its restore job", jobsRunning("restore") == 1,
    jobsRunning("restore"))
  local scratch = restoreWrites(function()
    return "same\n"
  end)
  exitJob('{"message_type":"summary","files_restored":1}\n', 0)
  check("the scheduled run published its result", verifyState().lastOk == true)
  check("the scheduled run is persisted", readState().lastVerifyAt == NOW_SEC,
    tostring(readState().lastVerifyAt))

  update()
  check("it is not due again immediately", jobsRunning("restore") == 1, jobsRunning("restore"))

  H.nowMs = (NOW_SEC + 3600) * 1000
  update()
  check("it is not due after one hour of a two hour cadence", jobsRunning("restore") == 1,
    jobsRunning("restore"))

  H.nowMs = (NOW_SEC + 2 * 3600 + 1) * 1000
  update()
  check("the due run begins by listing the newest snapshot again",
    jobsRunning("restore") == 1, jobsRunning("restore"))
  drain()
  check("it is due once the interval has passed", jobsRunning("restore") == 2,
    jobsRunning("restore"))
  check("each verification gets its own scratch directory",
    restoreTargetFromScript() == RESTORE_TARGET .. "/.verify/" .. (NOW_SEC + 2 * 3600 + 1),
    tostring(restoreTargetFromScript()))
  H.files[scratch .. "/tmp/data/one.conf"] = nil

  -- A tick while the new verification runs must not start a third one.
  update()
  check("a tick during a verification does not start another", jobsRunning("restore") == 2,
    jobsRunning("restore"))
end

print("== IPC: an untrusted target is refused with the validator's own reason")

do
  lsText = lsJson({ { "one.conf", "file", "/tmp/data/one.conf", 4 } })
  boot({ interval_minutes = 1440, verify_file_count = 1 })
  drain()
  local starts = jobStarts()

  onIpc("verify-restore", '{"target":"/etc"}')
  check("a target outside the allow-list starts nothing", jobStarts() == starts, jobStarts())
  check("the refusal names the allowed root",
    logCount("restic: rejected restore target must be inside") == 1,
    logCount("restic: rejected restore target must be inside"))

  onIpc("verify-restore", '{"target":"../../etc"}')
  check("a relative target is refused",
    jobStarts() == starts and logCount("restic: rejected restore target must be an absolute path") == 1,
    logCount("restic: rejected restore target must be an absolute path"))

  onIpc("verify-restore", '{"target":"/"}')
  check("the filesystem root is refused",
    jobStarts() == starts and logCount("refusing to restore over the filesystem root") == 1,
    logCount("refusing to restore over the filesystem root"))

  onIpc("verify-restore", '{"target":"/tmp/data"}')
  check("a target inside a backup source is refused",
    jobStarts() == starts
      and logCount("restore target is inside a backup source") == 1,
    logCount("restore target is inside a backup source"))

  check("a refused request publishes no verification result", verifyState() == nil,
    tostring(verifyState()))
  check("a refused request never notifies as a failed verification",
    logCount("error: Restore verification failed") == 0)
  check("nothing was written under the restore target by a refused request", (function()
    for path in pairs(H.files) do
      if path:sub(1, 12) == "/tmp/restore" then
        return false
      end
    end
    return true
  end)())
end

print("== IPC: single-flight")

do
  lsText = lsJson({ { "one.conf", "file", "/tmp/data/one.conf", 4 } })
  boot({ interval_minutes = 1440, verify_file_count = 1 }, { ["/tmp/data/one.conf"] = "same\n" })
  drain()

  -- While a job holds the guard.
  onIpc("backup-now")
  check("a backup is running", status().busy == true)
  onIpc("verify-restore")
  check("a verification is refused while a job is in flight",
    logCount("restic: rejected a job is already running") == 1,
    logCount("restic: rejected a job is already running"))
  exitJob('{"message_type":"summary","total_files_processed":1}\n', 0)

  -- While a verification is between "began" and "its job started" (no job holds the guard yet),
  -- the update() tick and a second IPC event must both be refused. The clock moves first: jobs
  -- derive their token from the clock, and a job started in the same millisecond as the finished
  -- backup would reuse its files.
  H.nowMs = H.nowMs + 1000
  onIpc("verify-restore")
  local starts = jobStarts()
  onIpc("verify-restore")
  check("a second on-demand verification is refused while one is starting",
    logCount("restic: rejected a verification is already running") == 1,
    logCount("restic: rejected a verification is already running"))
  update()
  check("the tick does not start a second verification in that window",
    jobStarts() == starts, jobStarts())
  drain()
  check("the verification still starts its job", jobsRunning("restore") == 1,
    jobsRunning("restore"))
end

print("== a lost listing callback cannot wedge the feature")

do
  lsText = lsJson({ { "one.conf", "file", "/tmp/data/one.conf", 5 } })
  boot({ interval_minutes = 1440, verify_interval_hours = 2, verify_file_count = 1 },
    { ["/tmp/data/one.conf"] = "same\n" })

  -- The listing is issued but its callback never arrives (a host hiccup). The feature must not stay
  -- refused forever: after the phase's own ceiling the next tick drops it and tries again.
  onIpc("verify-restore")
  check("the verification is waiting on its listing", jobsRunning("restore") == 0,
    jobsRunning("restore"))
  onIpc("verify-restore")
  check("while it waits, another verification is refused",
    logCount("restic: rejected a verification is already running") == 1,
    logCount("restic: rejected a verification is already running"))

  H.nowMs = (NOW_SEC + 600) * 1000
  update()
  check("a verification that never reached its job is dropped and logged",
    logCount("never reached its restore job") == 1, logCount("never reached its restore job"))
  drain()
  check("the next tick starts a verification again", jobsRunning("restore") >= 1,
    jobsRunning("restore"))
end

print("== the result survives a restart")

do
  lsText = lsJson({ { "one.conf", "file", "/tmp/data/one.conf", 5 } })
  boot({ interval_minutes = 1440, verify_interval_hours = 2, verify_file_count = 1 },
    { ["/tmp/data/one.conf"] = "same\n" })
  onIpc("verify-restore")
  drain()
  restoreWrites(function()
    return "same\n"
  end)
  exitJob('{"message_type":"summary","files_restored":1}\n', 0)
  check("the run is recorded before the restart", verifyState().lastOk == true)

  restart({ interval_minutes = 1440, verify_interval_hours = 2, verify_file_count = 1 })
  drain()
  local published = verifyState()
  check("lastVerifyAt survives a restart", published ~= nil and published.lastAt == NOW_SEC,
    published and tostring(published.lastAt))
  check("the counts survive a restart",
    published.checked == 1 and published.matched == 1 and published.failed == 0,
    tostring(published.checked))
  check("the detail survives a restart", published.detail == "1 of 1 files matched",
    published.detail)
  check("a restart does not re-run the cadence inside the interval", jobsRunning("restore") == 0,
    jobsRunning("restore"))
  update()
  check("the cadence still holds after the restart tick", jobsRunning("restore") == 0,
    jobsRunning("restore"))

  -- And a failure the user was already told about is not announced again after a restart.
  onIpc("verify-restore")
  drain()
  H.nowMs = (NOW_SEC + 2 * 3600 + 1) * 1000
  restoreWrites(function()
    return "different\n"
  end)
  exitJob('{"message_type":"summary","files_restored":1}\n', 0)
  check("a new failure after a restart still notifies",
    logCount("error: Restore verification failed") == 1,
    logCount("error: Restore verification failed"))
end

print(string.format("\n%s -- %d failure(s)", failures == 0 and "ALL PASS" or "FAILURES", failures))
os.exit(failures == 0 and 0 or 1)
